apiVersion: v1
kind: Secret
metadata:
    name: ovh-issuer-secret
stringData:
    applicationKey: ENC[AES256_GCM,data:nvTLX0yLitrLYVoCZBSUig==,iv:J5dfwqKFbnE2f432GzySQRACu7I/dIUo0Biq0TgnEho=,tag:5Yf7CQTF2eB1N5jC8igGVw==,type:str]
    applicationSecret: ENC[AES256_GCM,data:of1MdqE5ukQBKPK3TwIWoMShgsZ7qVtYYMJyThnG69s=,iv:HmOAowzeqPY33/M1Zgmnsl04ktHGaLHrNBckh30IMi0=,tag:4X/HyecTPOb7kRXqMUCUUQ==,type:str]
    consumerKey: ENC[AES256_GCM,data:MGqgCySpJXkfyrv5ZxRBaWQSz7Ov6JT2BFVRw94fM4c=,iv:lG/XkLndb4jZALJjkO2Bl0H+FfUBfwboT0PaUK7Ich4=,tag:sRtHK+dw3pjqTjGZsibmtQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWTBBTTZsMmhPanhJUHRE
            cnZhODl1K0dRVFVLTWoralpmanBDSUthWVFnCjhoUEQ4MWRGV2EyR25MbkpGVjla
            cUc4UVdyb3dUWXQ4SFlDY0k4WmEzRXMKLS0tIG9SZHJWNGhBYytlNi82b3RHVklL
            bGEvTWpEOTlYS3huaGIyYkdpYmZURVEKLxQ1suRjva1hX2GkD5cWtSzYvPCNWeI9
            lKjg19AlwGN0ceTwua0K1SnpIbWwTvF2KdTO8iDI15Hj/FPeIPrh4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T18:49:23Z"
    mac: ENC[AES256_GCM,data:UGy/c7lO9MCjMb9ryIP++qQddtQ7u+pOgGM+ujKlt3ePxr1nCUY9PWirwBiHmfU/OXNVvbcsEN3jLCGSfHVtgzrmV+GM9dNlAuDyR/vkt042nUhOgEC34Yhxdz3sPJMAAounXUhymUuufU+cgzplXLll+pHU3aSW9dvn/bVTl8E=,iv:IiF9XwFL2uH25Uoi6cUTLzrJSaZGgnMVzsMp9XgivyM=,tag:M9avmVyvmta1lr2Gg9JnFg==,type:str]
    version: 3.13.3
