apiVersion: v1
kind: Secret
metadata:
    name: ovh-issuer-secret
stringData:
    applicationKey: ENC[AES256_GCM,data:jm+ySLGK2DWk6skRbcfLDA==,iv:Eth3Z3GF8m/6D/No8mztMWGh/qAaNXUu50KuAGfor0Y=,tag:XWHdxvnkJZfRrKlIjnAznw==,type:str]
    applicationSecret: ENC[AES256_GCM,data:SgTH1BRCJI2mv8kq81NmYjY4DcTazUeoKIigm1J2RlY=,iv:wPM/KuX5AWcM3ZE/1ml+ZX/xbfcBL/fYN9D4xwW8po4=,tag:Bt7Ju9tXutkpx2ITKMcHjw==,type:str]
    consumerKey: ENC[AES256_GCM,data:VwA1Ccc0cRpxxY5vATvy7isjSw9nezzG1690s3m4nr4=,iv:16a/cXGzTEcLubOgb0pTIuBbtQI9Aet6Zy9N9UO8qHA=,tag:1aHjd2tVV+Afeo2yVhj/3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWTBBTTZsMmhPanhJUHRE
            cnZhODl1K0dRVFVLTWoralpmanBDSUthWVFnCjhoUEQ4MWRGV2EyR25MbkpGVjla
            cUc4UVdyb3dUWXQ4SFlDY0k4WmEzRXMKLS0tIG9SZHJWNGhBYytlNi82b3RHVklL
            bGEvTWpEOTlYS3huaGIyYkdpYmZURVEKLxQ1suRjva1hX2GkD5cWtSzYvPCNWeI9
            lKjg19AlwGN0ceTwua0K1SnpIbWwTvF2KdTO8iDI15Hj/FPeIPrh4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T14:11:46Z"
    mac: ENC[AES256_GCM,data:17G9WNT8I/J3cgKie62yQpkjIHSIhJ/hTcFgSlrX3CeRhrqQQJ/+4Va3B4wwT1tA3WxV5saRX8uOBadCY7JD9XcYxlAupfaEauaVxwNruQ85OWE1dnq9ZliI2mWDuKdkFH430dK1cjqO0SeVEx7/T9BjBV5TO/d+/cme48uSFN0=,iv:8ElJM0zjaYkMC3I8HAe/o94kGB9Qva71KjtDc1ZxbQk=,tag:9hLVNuylNzLefLgP3v8xHQ==,type:str]
    version: 3.13.0
