apiVersion: v1
kind: Secret
metadata:
  name: ovh-issuer-secret
stringData:
  applicationKey: ENC[AES256_GCM,data:tDZCD9tNWx154Z/udbFxHlFTRQ==,iv:rXKxtUPMQftrtoAxHEj4oyAfhqbKj6JR889BdwVyLTk=,tag:iiqpIfrW/ZKWwJnHFOQh2g==,type:str]
  applicationSecret: ENC[AES256_GCM,data:/9ihBTtvNeeszvLXP2Ip/mKtnS+0VGDNXemtv2L+r3Y=,iv:VuUI0wue8um0qRQ4vxT6OocDJN3Bs6WK844ElDxf3Gg=,tag:QmmZIALuxyqVPLcHxZfLtA==,type:str]
  consumerKey: ENC[AES256_GCM,data:VwA1Ccc0cRpxxY5vATvy7isjSw9nezzG1690s3m4nr4=,iv:16a/cXGzTEcLubOgb0pTIuBbtQI9Aet6Zy9N9UO8qHA=,tag:1aHjd2tVV+Afeo2yVhj/3w==,type:str]
sops:
  age:
    - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWTBBTTZsMmhPanhJUHRE
        cnZhODl1K0dRVFVLTWoralpmanBDSUthWVFnCjhoUEQ4MWRGV2EyR25MbkpGVjla
        cUc4UVdyb3dUWXQ4SFlDY0k4WmEzRXMKLS0tIG9SZHJWNGhBYytlNi82b3RHVklL
        bGEvTWpEOTlYS3huaGIyYkdpYmZURVEKLxQ1suRjva1hX2GkD5cWtSzYvPCNWeI9
        lKjg19AlwGN0ceTwua0K1SnpIbWwTvF2KdTO8iDI15Hj/FPeIPrh4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-11T11:56:29Z"
  mac: ENC[AES256_GCM,data:VBm41DwdfLWC8ylQZqUUsC68LwV6egarZfYQv2yvI2x2XaIrjiBc3uTnqFJ6i80+J40LJhgFRKJ4MZUkVM2iFcrEn3NLHBEUWa11npX4QmAHyLB9MnC2SdB8GPhJ09c3+19lvaiGPCIyXzgkc/AJGrBc0RyoT8MxOTtY+pQFnpM=,iv:l/JeyS1jvlhPgfELJngQ4spbQiBZ1AEbdARYOEq1CiU=,tag:64pmxRxP7BTx/luxwGRESg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
