# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-credentials
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes
  target:
    name: ${APP}-kanidm-oidc
  data:
    - secretKey: key
      remoteRef:
        key: forgejo-kanidm-oauth2-credentials
        property: CLIENT_ID
    - secretKey: secret
      remoteRef:
        key: forgejo-kanidm-oauth2-credentials
        property: CLIENT_SECRET