apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-kanidm-oidc
stringData:
    key: ENC[AES256_GCM,data:wdjl64wYZw==,iv:kPSOIS3K7uaml1He3tWvnVGmATECaKfeiteeflvAfS8=,tag:IP37O/mANpRPYIeOq7VzSg==,type:str]
    secret: ENC[AES256_GCM,data:S7nFrbh4ox5e+D+J2EtYieszmblYCTCz1Bxcise9nsm9RXgpE8j4NeAtAahG3EIs,iv:8qQ259MJnx7fEN5rvvKjs/MbQlYiOlxtpmPeBx3GSAY=,tag:jtn0/qQga5dGdQYQXwyOvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWXhoNnJJYXBKZWZGTjhH
            SHIrUks5cEVvdjdvK0VyeXViNkFLTU54c25vCjR5ZVhIcUdiVS9sTHh5STNPVGhi
            OW5BMmcvUEkxQXZ3cnc4NXNRL3FoeHMKLS0tIERTSnMyMmdlT2ovUUZ6bVhaQlhk
            Mys3Vm1TdCtWam9GdUE1c1YySGdyRmMKRx9oVohYj5mJFGTq237jO3PICR0yNIsG
            PVyR9okFi3K/Ve4w3yZ6mxSH2eeW5mcDxTEY2GPG0FxaftSTUvqvdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T19:56:14Z"
    mac: ENC[AES256_GCM,data:llqgCO+q134AgU7znFxHtKXefWRPujmEAntZwkwWYlGhNh3xQD4O+gb8UsnkWft5HgATUgMHZbkgKiIvzdHW8XPCBNsCIpPxGSvHrGHa4h8+LMwDIXUMGDyovnpj/z934PI9onfOtF4+tSwK+gdJrJ2hRfJ5aQlcCTBTsEyzxzM=,iv:loh6RMQxUgRqA0CeQj0OJjHvyGuFZHZGTvogcX7jbrA=,tag:a5b2pDiy4ooKY7BmkxJEFw==,type:str]
    version: 3.13.1
