# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: "${APP}-forward-auth"
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "${APP}"
  extAuth:
    failOpen: false
    recomputeRoute: true
    headersToExtAuth: ["Cookie"]
    http:
      backendRefs:
        - kind: Service
          name: ak-outpost-envoy
          namespace: authentik
          port: 9000
      path: /outpost.goauthentik.io/auth/envoy
      headersToBackend: ["set-cookie", "${AUTH_HEADER:=x-authentik-uid}", "x-authentik-username", "x-authentik-name", "x-authentik-email", "x-authentik-groups", "x-authentik-entitlements"]