apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    uuid: ENC[AES256_GCM,data:W1IaTt9/OEEEoEc59t/oe4RXxVuCAYebCd89rOshw36UiHLE,iv:WklzprZaOlnaOA4OySn/pPxKLzfvekav+RKuwWtE6SA=,tag:w0PceD6vYp/SrDnjEjzZig==,type:str]
    token: ENC[AES256_GCM,data:qX97kZZuMI8ySbvpuetA8T9XRkIjSS6SyE3zew2WwD87YwaxGJRtrg==,iv:DvTpyaGt6DT/3SHSRpN/xKWvoMZLmOggYo7Tle2WnX0=,tag:9iBt852bjPrCQy5Co6KtYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdmtyS1RlVEhJUVkvYTBt
            bDdiV25yK3ZXNHA0dWdxSURZbytYTkd3VzFzClFrUlJJQlFhcnRjdGlUd2c0Z0ww
            emd2OWFPejAvWUw1UVFMMHRLQjZhcGsKLS0tIDlsa200WWRKVCtvTER3Y3VuNi9R
            d3Q5TmltWXNZWHBVMmU3R3ZvMnhHdDQKyult0EBwXxa7tQLxq8TkwicLd7CilNUp
            cH4ywIYw0zvCgGd+3doz6mGLpaHZN8nIblQMigeFo2LtEqsFnf8Aug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T10:07:34Z"
    mac: ENC[AES256_GCM,data:B5pRH7i4+abE7g3YUd/F6srtvvp3Gkdu/ki+cpDrk8LXD8zIeunBgxxWCnu/t7tb1UDFi3ZjtbLcoO8zTueZHthRkGP+tTwD//2g1U0qWIrH5Ji8rr/gYmV1NIkuQe7armxBBz9yD2jiHvoBk1KeS4BFJ9vLUYySQmAJ2lXx08I=,iv:Mqob9KTlcRxrUMuag+RIblWqLwSu6u33tcA2qJ8au7U=,tag:+lSoguINPNBb4YYNOIE+Mg==,type:str]
    version: 3.13.3
