apiVersion: v1
kind: Secret
metadata:
  name: nasbackup-secrets
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:WV9/AsxtTA==,iv:dQGM0s50Jyo9/8+Zoy/8jTNbQsZJvAJzDIYTOY+poxc=,tag:WeEcwd54HJq7ZmqERcVAZA==,type:str]
  KOPIA_CHECK_FOR_UPDATES: ENC[AES256_GCM,data:b1mrC80=,iv:n2B+Ma/BZodgQ5OuhIN9VKRQo5yT1FEVUcQPJKY3cD4=,tag:OLHwLkRn8Sc0r7ZIft0+sw==,type:str]
sops:
  age:
    - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcEdyZlUrT3hxY0ozNm5R
        OFhJSHhMZjNMSXR2OEN1d0taWW9lWjYrRlZRCjlrSU5FZHJacHk1S2FqcDJKM2sy
        WHhSVFB1cExobmUzZFhNc3RqTDRyZU0KLS0tIG1pd0dQZ1lBWGxKeGc4ZGpaU01t
        S09wMXhWckEzVVpOV2tlQnN2U3NzRjQKSXs/ssWGoA3QpJzwfAfO9uy9jRNmjqQu
        TthnMxvUrgqkejJvg53DeBYGj7LzV8ovGhG1ds1kz2VWddMpnjxSvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T08:21:35Z"
  mac: ENC[AES256_GCM,data:j+pKl4G8muXJJyGl8gQeBBJu1XsIsQ+fpI2/dT6VkYqbjw/+r/cOGsLBseBI69Lxhd98/8b0FyXH2KwaSrq/nuCpZ2WxRCNPACu7Hcpu0+3+m4mQOZWYscDEa/uYueg4GSFlxze7IthSbnKh60TJUTIIRzN5rOwhFMvjlYz0d/4=,iv:VXC7hgSI/BJXaOcUndwIa4TXP3OcxvoPsmWlMlwYPLE=,tag:SjcHGRIJyLuZJIU8zD0Viw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
