apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:VIyOyPAz+HJ84muQ,iv:Wah8QEZkhuwo8ew2KXv+JGHIK/mArP6/Vkxni8vmW88=,tag:kTJ6aAsobbDkXHPvPfI5eg==,type:str]
    SECRET_CIDR_LAN_V4: ENC[AES256_GCM,data:TlnGGsP60VMcsENDvps=,iv:Cp7+U2ecTEXSu0VKaEPQZPRnHRaC0dqEarV+J8Gkxfw=,tag:ubPuOvGI6yfMWRPdjnK3UA==,type:str]
    SECRET_CIDR_LAN_V6: ENC[AES256_GCM,data:CC8Yy13tLlMqT1X6peHUht5XCelPcQ==,iv:/84BxyL0mx5Uh6JxuWYbX0aukmQ8wdT4957B74h+zyU=,tag:iXf1S5Txrf2HgTnc7yoW8g==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:i+6Qyv39jbOQkWjrLUE=,iv:oFtb3u6R1ezDAuZz/aY8DDZgbV987qTHszEFlWNFTDw=,tag:ov5UdAuTcNYvixSbjhIbSA==,type:str]
    SECRET_LB_POOL_IPV4: ENC[AES256_GCM,data:7FTBHRRo/ueKfIzw3Cs/,iv:XFuZ4958GpkuNcmpQgqjo8y/aaHuc9dXrZIxaUeh004=,tag:j6qv69G+JomHXxA5XPgMRQ==,type:str]
    SECRET_LB_POOL_IPV6: ENC[AES256_GCM,data:JRX3xZbedWbxrEsZXh86RzPzhsfDsT8Ygw==,iv:DSIMu951GCcGZvKd1F82pzEHuv1cgGFqFsjADSn6sHw=,tag:YfqZPzq4D75BBdwoGSoK2Q==,type:str]
    SECRET_LB2_POOL_IPV4: ENC[AES256_GCM,data:/bnuqFGU49D4ZPhb7QEl,iv:0hUpj/oSoQCYUTWgyAJhpu+ljONFZZtc+/IZprCNdP4=,tag:mpeaqoVOIFWiVNiDw+eCfw==,type:str]
    SECRET_LB2_POOL_IPV6: ENC[AES256_GCM,data:GYPwGd4tdiJA03vPoJAbOkoeT2EBylr+5w==,iv:DzCicZ74agPtVxqk54KCzvilCKzhJitYU6usAYFO9/s=,tag:uvnXmf/+0JGDwPinwgRv4A==,type:str]
    SECRET_LB_IPV4: ENC[AES256_GCM,data:55qPpyeuDciUYw+7,iv:uB2QdK8/jQEuVoc4vH9ySyXayVCBA14TvNe3q7PKkco=,tag:dDsYrAKPvD/YRQOkai8cnA==,type:str]
    SECRET_LB_IPV6: ENC[AES256_GCM,data:0OZ8sVN1WQMYE9sqT3OaapTyWLZv,iv:nnV1HcA0fC9rak64EdEuVZNBfMMZ+rbT6Ugc+9UJKWU=,tag:iA5Ml+AOT6sZasWb0P1//g==,type:str]
    SECRET_TALOS_VIP_IPV4: ENC[AES256_GCM,data:xR8MvrjPdBpjCDZ8,iv:z/9sTdbLhPSbfH4tAgosvXxJkH8v/rGGcpSEvtWSxI0=,tag:ZVFWM5Tdud2P8QfuF6G+jw==,type:str]
    SECRET_DS416_CIDR: ENC[AES256_GCM,data:de2qoHMgZwevQq07aRY4,iv:Tpa3RBBfxXLjXMMHkQgzYry62IyFkeQhRPdN3tqb1ks=,tag:0DrFkhcolEtGFdHVq41KCw==,type:str]
    SECRET_DS416_IP: ENC[AES256_GCM,data:wTd64Z2s4KCS/xQL,iv:7z0fqMoqNgvCSf2QN+4y1oD2HCWfBq/wfTbhinaMYnA=,tag:/iaEHzCWJG7jtBII7+BAsA==,type:str]
    SECRET_DS418_CIDR: ENC[AES256_GCM,data:iYiyLxeGjWXHgYYyxfof,iv:lrmpK5V/vjPhcLIGp7OJ2PdROX2+k9FAZPNwMfWTwu0=,tag:EDm/7aAHMQPImBHQ2KCT2g==,type:str]
    SECRET_DS418_IP: ENC[AES256_GCM,data:K0L+WnTS7N8HgFSN,iv:LRdX9+kvSJALKHSTuarEp4t5BIR4wb3Najk04245Vjg=,tag:nbWktRGYC0lKTLNCC6b3zQ==,type:str]
    SECRET_NODE_IP_TATSUMI: ENC[AES256_GCM,data:XreDtGc41zaOBC6c,iv:OWrnYogC3+Nyd6Fo0wAKHyoi8NT2QBWy7+XxcFZjJuM=,tag:nXhim8/JATWqPfTtHyIysQ==,type:str]
    SECRET_NODE_IP_LYNKA: ENC[AES256_GCM,data:1MpJiVjgwOmINSgD,iv:Kr/tpUzKD1Dsvbz82i7sGiQKa7yviKTCSNA+vskk/qg=,tag:nd7RpzMuJ1xzCQApEWH7zQ==,type:str]
    SECRET_NODE_IP_ENIGMA: ENC[AES256_GCM,data:ZejJHzpZZMDwDYPp,iv:D1o6h0BUcMjo3wwdUb2bm+vUwsQDhxgmL1J/EBr7IOI=,tag:ysPuWGv2iPBrR69HGjgmcA==,type:str]
    SECRET_GARAGE_WEBAPI: ENC[AES256_GCM,data:OrcSNOn1OK0l9QZUbJ/oy5RoBk23K1l1,iv:VN6xJh9+IM2DJ2/9XEHNVXyViJmm803iO5xpW5NOCqs=,tag:NXkhjGC02fFbF+A+t7sv8g==,type:str]
    SECRET_GARAGE_IP: ENC[AES256_GCM,data:ewMPqDWoC4AOWAlf,iv:gmWcERJiDJKqEZmUj+mPgUvp4307sf2xWHoH5KGoXFU=,tag:RQM68j6+JIn2IzqsgiaG2A==,type:str]
    SECRET_TRUENAS_CIDR: ENC[AES256_GCM,data:ICzAY8iCa9Bpzc+iCv7e,iv:6vXdrCNXPj8GuVcdU5V4zqF3CzkRG7edo55Dzs8LGPc=,tag:AZgiidArXDEb10XasulSLw==,type:str]
    SECRET_TRUENAS_IP: ENC[AES256_GCM,data:HqTEnWmbbmBXyBFB,iv:gXW6qVytkR9vlLvCToI1cYEJrbfI41/H5GYWPmzhXzw=,tag:BlSuPxdVMi1P31qQGUC66Q==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:r5co/hU/55eBwV3hUx/kJXeOtfIrRN9y97ufmZWfxeHtZ2jC4JKHBmOI4Cn+JqCs,iv:gucwxFcgvw3c/YBDtydkHSzFACa2wP0CqXYUIhzEewE=,tag:syZem5VAytCnYWuHwuicPA==,type:str]
sops:
    age:
        - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncXg3TjBRaXAweUsyejFv
            OWRqYUo4SG50MXlyYkN1RWI3S1JuZS82UUhZCkNaWmFBcjRmMVRkMnN1N0lnc3dx
            UmJiSDM5SUJZT01uVlpKejFGVXJWdUEKLS0tIDN2UDlwbTh0VEp4ajJpNnA4am9m
            d3hYN1YzVmp4UUc1NEtOanZGOHA3RnMKMemkkwI02VUhFHq87DEdOzKolqCRWwW6
            L6dqvCUefXLucu7nXMzq/H+InnV0sLInPiyCFwNq9nJqafFd+3qAsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T12:53:02Z"
    mac: ENC[AES256_GCM,data:wSHMeWf+fhFhwBXAdTE4oeIETKxlA9acdMjnOPGs28B1Gx8k7dSh1/Zg6WtEqX03X7A22opCQHjpTDLpW2Z7anzAVLh+UC6MOcWcR2bkDperPze0Cx2Twcyl1gKCL+AWnlumVlEHYssMyqdrLxypetxFwo7u5cEXTjxvwex+4bc=,iv:wPMcyauK6OOrNzXrHoBKJiVumEhrfFTq9JXtlihjCr0=,tag:h/bMsS5H5CZm2edUTB6W9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
