apiVersion: ENC[AES256_GCM,data:clA=,iv:BBfENyoR7TNscBlZ1DL6Fb7asy8GONU0wdzTn4JVYK4=,tag:PAo7k1cKoIFeFqtWjaEw5A==,type:str]
kind: ENC[AES256_GCM,data:5rixCMxa,iv:FXrcskaCreu4wM1Q2xAu5ZQeAdwtqNwthAcx/uPugR0=,tag:grI8N9pYFxqSd85gexoerw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:S1LVPh7WeOVSpEZoEFqu,iv:xM+uco07PDrpZ3y8vfM8peVKg9NZoaaiBcPruYhWmSo=,tag:AP0iP6RrcEEykZRrscZYWw==,type:str]
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:v3A8oagCJkrP016w,iv:Ocmrfw0QBD3s9F4E/zpRB7ADJkynWhMi70fz5NwA0yA=,tag:+J3qO2HRA5UijRMYXCZatQ==,type:str]
  SECRET_CIDR_LAN_V4: ENC[AES256_GCM,data:OLPYjPguxphJ4ioXHko=,iv:Y8LKjj+8iyw6rdiXQrfR2sNm4PmwVilkRgZtnyR7HTI=,tag:3zM9BUowxqOycC+eoXJPcA==,type:str]
  SECRET_CIDR_LAN_V6: ENC[AES256_GCM,data:5DMqElIKK8eDZeW7+RNPX+KcMH8UNQ==,iv:ZgMqFgSfeR9ksKro60luVwpHgwLzob9DPrxf5pTGdAQ=,tag:HkQYTMCRqka90Z451kcdhQ==,type:str]
  SECRET_EMAIL: ENC[AES256_GCM,data:HUe2ahTe+1ewiChm0n8=,iv:I+22/SvaLTH58Olpm9p5eUUkrWGhiKWbQtvcLQjIgJA=,tag:J1fAoSeihYcpgW/4TQf9yw==,type:str]
  SECRET_LB_POOL_IPV4: ENC[AES256_GCM,data:AvjSxchELYtn37julf4u,iv:M+jMueejgkCbS0BVNPWdF5DIzAnIPhD+TIDLUrpc+ms=,tag:W3LDBVX7KB8oaiSXoEJSWQ==,type:str]
  SECRET_LB_POOL_IPV6: ENC[AES256_GCM,data:QQqdKodRnqUkNXEgfTUV2RHWyJLJ50b0XQ==,iv:j3cVzVNZNXRxGkxj0rD7tMT3F3McfCrpsLjP4lbNgP4=,tag:8fNRuUjsW/TczAAxzmI7zA==,type:str]
  SECRET_LB_IPV4: ENC[AES256_GCM,data:H+LU+fUIxZyHTtyO,iv:cywgK7gDDNze+m8gqmzZ5cAwKuP6mAKzkQ/mNI8Ld6g=,tag:Q2JueO9OGvdWL5z09wavyQ==,type:str]
  SECRET_LB_IPV6: ENC[AES256_GCM,data:3GG9GJfMM0u5KPW0ZxsC0NaZxiW/,iv:87M8a3+vI9EA+vjrBUAOw0QXjOoHz8YwZ38V3zaSjew=,tag:rCvRAqqchx3ATcQlDWwYYQ==,type:str]
sops:
  age:
    - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQW1PYncwSzNrTUxkTEwy
        TXVWUXltaEYzOFVVbWgxYXd5RFZuL3F6eVNnCnEyZGNsMVFlVy9RMDh6RGdKbFls
        SWRIcGhVUDRSVmtzeVZ0M1FJMHFrdWsKLS0tIG5WZis2SFZaQ2oySEh0cU9VbWVu
        S0Y1RkdMQkJ4Wm4yM1VGQkw3OUc5ZncK7K9dAPZkWWSOIp5+uYkBKp5duYLlCxIe
        0WoigFnLwayy7kucI/uoA9F0E8zwnDAUt2yDZ72aWWK8X0HaDjWmBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T20:03:50Z"
  mac: ENC[AES256_GCM,data:nGX2TtHYsvRw9Wls4adsxPLXpUx/hn70PYb0enxP3Mw3+86Ym4Ujb1fde+7oylThEjEA1Ir/yh0YeNem0etL+yZaDCh28COmWx2kfd2Jp2bdAtx2g2COuHe/kcNdCMBbj3xnSBmMwgW0iFl5Em8wlW8v3cjk/XuZFdqwgXLywIo=,iv:kcbDe0nfYAbUYgDMKGmZGUUrgrm742kXiJhOaxq8JBM=,tag:82m2WAKN9wXA8kDN1iC3bQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
