---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cross-seed
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: storage
    - name: qbittorrent
      namespace: media
    - name: qui
      namespace: media
    - name: prowlarr
      namespace: media
    - name: sonarr-anime
      namespace: media
  interval: 1h
  path: ./clusters/k4/kubernetes/apps/media/cross-seed/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: media
  targetNamespace: media