apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    RUNNER_NAME: ENC[AES256_GCM,data:S6XtLJPMtCOu+ZShQNHId9FNplOUg8CgI4k=,iv:FTZgTlYvsL4p6yuQJNOD3Tae97n/7+lm0eC+gMmSgDU=,tag:Hjy+bS/9UMxaRrkxWdhAww==,type:str]
    RUNNER_TOKEN: ENC[AES256_GCM,data:1gppMLsJiBTm3s1nC94xlCrqP3WD3+UhuAj6AjnGHj+M7I4WpFQOBw==,iv:i1OYbdYrnQd5U5bzrT7Ia0phQjNsq10cCYQC6WXNWl8=,tag:qcOPkFNs9gq1yhkO6mmdzg==,type:str]
    SCALER_TOKEN: ENC[AES256_GCM,data:SwqOMqUu79ikCLRQWjSKWLmuibS6s6UmIeMG9j2nMi+7aNSEImsp5Q==,iv:YgZU/qz0c0M7taKwwhZwdRHJbC8FwyReJu091muJcBg=,tag:B0INGozlo6StU7hMVGdaKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySkYwT3BnNDA2YVdSblZq
            bGZtb1g1VkRoVCtrVDJCd1o4WjhjNTR4ZEJVCnp4eWh1bWQwL1VPUTg5dFN0UThI
            cEU1KzVhbnhtcTI3VkkrWlcrNGpIVmsKLS0tIE55YjBYMkl4RysxSHNvUkluTlNl
            Nk1rS0liNTA4UnZJNXNyRW1TdEIvUjQKQ29dLsD1IU6LDNkampivzS75EFBA/t7P
            M/qGGxof8i3xRTVlyzxbsRqMNBgarCppLEpLESS1YNvgRZuE4qWlBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T12:23:40Z"
    mac: ENC[AES256_GCM,data:WDDpfL7QJZb9kMALpvtUZe67SeC/PJ77aOgEgqb2bA/6py+MV7kJCEM8NYBwGnIoNmzzeGXIpGrTM25qNIntiX5DpLaNCJoiqP7EtDhQbn4H8WtJmmPZLcQA2U1Zx7AzMidW+ytivabkNmKNjNLNJyzk1fgojKz12y9YfMuKDYo=,iv:6+YFAY0pcmCqGVwt+HPLLFU+RqCwMEUbp1rO/9FnvlY=,tag:u7GZtA2k/rs6X5tgKYgJZw==,type:str]
    version: 3.13.3
