# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-kanidm-oidc
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: ${APP}-kubernetes
  target:
    name: ${APP}-kanidm-oidc
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        provider: |
          [
            {
              name: "openid_connect",
              label: "Kanidm",
              args: {
                name: "openid_connect",
                scope: ["openid", "profile", "email"],
                response_type: "code",
                issuer: "https://idm.${SECRET_DOMAIN}/oauth2/openid/gitlab",
                discovery: true,
                client_auth_method: "query",
                uid_field: "preferred_username",
                send_scope_to_token_endpoint: "true",
                pkce: true,
                client_options: {
                  identifier: "{{ .CLIENT_ID }}",
                  secret: "{{ .CLIENT_SECRET }}",
                  redirect_uri: "https://gitlab.${SECRET_DOMAIN}/users/auth/openid_connect/callback"
                }
              }
            }
          ]
  data:
    - secretKey: CLIENT_ID
      remoteRef:
        key: ${APP}-kanidm-oauth2-credentials
        property: CLIENT_ID
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: ${APP}-kanidm-oauth2-credentials
        property: CLIENT_SECRET