---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ${APP}
spec:
  interval: 1h
  url: https://charts.gitlab.io/
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  chart:
    spec:
      chart: gitlab
      version: 10.3.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: ${APP}
  interval: 1h
  values:
    global:
      hosts:
        domain: ${SECRET_DOMAIN}
        https: true
        gitlab:
          name: gitlab.${SECRET_DOMAIN}
        pages:
          name: gitlab-pages.${SECRET_DOMAIN}
        ssh: gitlab.${SECRET_DOMAIN}

      gatewayApi:
        enabled: true
        configureCertmanager: false
        gatewayRef:
          name: envoy-internal
          namespace: network
          sectionName: https
        installEnvoy: false
      
      time_zone: "Europe/Paris"

      deployment:
        annotations:
          reloader.stakater.com/auto: "true"

      edition: ce

      kas:
        enabled: false

      keda:
        enabled: true

      pod:
        labels:
          ingress.samoth.eu/envoy-internal: allow
          ingress.samoth.eu/keda: allow
          ingress.samoth.eu/vmagent: allow
          ingress.samoth.eu/kube-apiserver: allow
          egress.samoth.eu/database: allow
          egress.samoth.eu/envoy-internal: allow
          egress.samoth.eu/kube-apiserver: allow

      psql:
        host: pooler-transaction-rw.database.svc.cluster.local
        port: 5432
        database: gitlab
        username: gitlab
        preparedStatements: false
        databaseTasks: true
        password:
          useSecret: true
          secret: postgres-user-gitlab
          key: password
      
      redis:
        host: gitlab-valkey
        port: 6379
        auth:
          enabled: true
          secret: gitlab-valkey-secret
          key: password
      
      registry:
        enabled: false
      
      serviceAccount:
        enabled: false
        create: false

      gitaly:
        internal:
          names:
            - default
      
      appConfig:
        artifacts:
          enabled: false
        contentSecurityPolicy:
          enabled: true
          report_only: false
        defaultColorMode: 3 # System
        gitTimeout: 3600 # 1 hour
        lfs:
          enabled: false
        object_store:
          enabled: false
        packages:
          enabled: false
        uploads:
          enabled: false

      # omniauth:
      #   enabled: true
      #   allowSingleSignOn:
      #     - openid_connect
    
    # end of global

    registry:
      enabled: false

    gitlab:
      gitaly:
        configuration:
          git:
            catfile_cache_size: 100
        dailyMaintenance:
          disabled: false
          startHour: 6
        persistence:
          enabled: true
          size: 5Gi
      migrations:
        extraEnv:
          GITLAB_VALIDATE_DATABASE_CONFIG: "0"

    installCertmanager: false
    
    certmanager-issuer:
      enabled: false

    prometheus:
      install: false
      rbac:
        create: false