# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: labelled-allow-egress-kube-apiserver
spec:
  endpointSelector:
    matchLabels:
      egress.samoth.eu/kube-apiserver: allow
  egress:
    - toEntities:
      - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
            - port: "6443"
              protocol: UDP
    # - toEntities:
    #     - host
    #   toPorts:
    #     - ports:
    #         - port: "6443"
    #           protocol: TCP
    #         - port: "6443"
    #           protocol: UDP