# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/kyverno.io/policy_v1.json
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: pss-baseline-special
  annotations:
    policies.kyverno.io/title: Baseline Pod Security Standards
    policies.kyverno.io/category: Pod Security, EKS Best Practices
    policies.kyverno.io/severity: high
    kyverno.io/kyverno-version: 1.8.0
    policies.kyverno.io/minversion: 1.8.0
    kyverno.io/kubernetes-version: "1.24"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The baseline profile of the Pod Security Standards is a collection of the
      most basic and important steps that can be taken to secure Pods. Beginning
      with Kyverno 1.8, an entire profile may be assigned to the cluster through a
      single rule. This policy configures the baseline profile through the latest
      version of the Pod Security Standards cluster wide.
spec:
  background: true
  rules:
    - name: pss-baseline-rule
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE
                - UPDATE
      validate:
        allowExistingViolations: false
        failureAction: Audit
        podSecurity:
          level: baseline
          version: latest
          exclude:
            - controlName: HostPath Volumes
              values:
                # fluent-bit
                - /var/log
                - /var/lib/docker/containers
                - /etc/machine-id
                # node-exporter
                - /proc
                - /sys
                - /
                # smartctl-exporter
                - /dev
            
            - controlName: Host Namespaces
            
            - controlName: Host Ports
              restrictedField: spec.containers[*].ports[*].hostPort
              values:
                - "2020" # smartctl exporter
                - "9100" # node exporter
                - "12345" # fluent-bit for talos logs
                - "12346" # fluent-bit for kernel logs
            
            - controlName: Privileged Containers
              images:
                - quay.io/prometheuscommunity/smartctl-exporter:*