apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-secrets
stringData:
  OVH_ENDPOINT: ENC[AES256_GCM,data:7Bd7Brvl,iv:YyEnWpXel3dqhrKnVxHFwQvRQJ5zIdXbbMO4N/DSesI=,tag:2L8+dJ+2yaKUzVmTzt4pPw==,type:str]
  OVH_CLIENT_ID: ENC[AES256_GCM,data:CvSInJuevfcBvMF6Ls1yv96hkg==,iv:cfE4gTeQl0VTNjI8lfPngPHSIQL87wPvarCNyltd7E0=,tag:wF8ZP3N3UQj1XC262nyP3g==,type:str]
  OVH_CLIENT_SECRET: ENC[AES256_GCM,data:/Isbmz+CxZh8LAsacyr7CYhxkt6oOIjedzoUx4S38Qg=,iv:kxp7OxF0HTjNAz0j572vkBBbTkpxC0UXydqe1lCjmoU=,tag:up84JodLSQGI/5L1lMzULQ==,type:str]
  OVH_ZONE_NAME: ENC[AES256_GCM,data:w+UTQoSL3LEk,iv:C+v6DsssSpt8NRP4D6554txCIz9BMYvnxuAMvT/jy+M=,tag:RlxF7hmQzdASDlkrOSnJpw==,type:str]
  OVH_SUBDOMAIN: ENC[AES256_GCM,data:PBL3vQ==,iv:kVcrOl9YKBROJDXBnkfvUFbYZLDOw0i2AQBYaAA+Lyc=,tag:9DqTE41UBCraJnjhz6GAkQ==,type:str]
  OVH_SUBDOMAIN_TTL: ENC[AES256_GCM,data:JYE=,iv:3ySsXfFwxRP85RSA58M5DZPw+blK5SR3/BlU7P0ZjCM=,tag:e/r2Ky9KKpYJzRNUR868oA==,type:int]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTVNJeUg5RWV2U3Q2MjY1
        NFBJU05mbmZ5N24wNnNGb3Z3a2I3dEhvaGxRCkRsS1AxL2xxcldKSlVVTkVnZUY3
        REhmd2cvYVQ3MHRXNHNpOXFFbElhT1kKLS0tIEk1Uy9GbEd5OFFwWEVPL0grQlVR
        WUx4Rmx0bUZYdHV5ZUhXeDRVV2tjYWcK3u5m1xNB4Cpj4CK3JXorti0sCfeHQCIU
        Bm5DnIfUonc5Bsq7gm5Bt9/nLAA6Wj638pD3von7dVYcsdYbo/3UIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T21:40:21Z"
  mac: ENC[AES256_GCM,data:BHM7D+3PdYMKRYvoC0XLWWUp5jlOvg9sI5T1obGID1Ida137LT+Qg62jk/640PgBBWKFStR2gFl0Y9kFqkoNGtVk7ruAkCOglIXvGZn3ze5FXF3CqVEFNhPQttwbbvS6DzSeiT/vxWmSDYKEkScsi0fC4IvP8NiqqQEje3y1vjY=,iv:eLlOzpXyJ16Ms6Ua7jaqLrPO7Y2i3g2Hr2SltL3RbOk=,tag:zkXZiofGjm4QCC+qCVWzBA==,type:str]
  version: 3.13.3
