apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    api-key: ENC[AES256_GCM,data:R7RZmHxPDAL40xJJ2MYKHP7n95WtYSRJJ35NUG9KTLUcNID5BdiHQ+z/7Mb18OzwDlE=,iv:HjIWnVHrPduIo8cPuF7pTCd1j25n3piBFd8f0wZnJSI=,tag:6a2YCeQT6GY+w/zRz6IrAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeWM5M1VBMC9QUkt0cHZu
            K3dKRXQ5TElHbzRudnRsRU9Takx3bnFUNGtRClF1RkhNcVdZaUhJMmR6RDJPN21t
            dUUyc0hBQmdid3ZVZkJGOWhYSXc1bE0KLS0tIEJ6ajJWb29kOW1kSXd6WHVvbmFI
            dW96RWFUVGZzM2pnQ1d2Mmx1MVY5YlUKvF/ha4msksqdcDbc91Y3DLzN44XF3vev
            hBC6pyyTPGDN5SNRwOxQRb4wshd1elBUvppiM4b1qCLWEHBn+334JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T12:51:19Z"
    mac: ENC[AES256_GCM,data:GhZNHgxgAKjYIvVpejRc08LHQgb8z6gMZSHTiIBpJ2357CPOW21Y6xcowYjPh5OfX66qItlzI/7AeuifXheeelnGlqJ9YZC0KzZBO7VdAXWXiflJG/MxM0kFT7n4zADHghtBW9jn/ta1z0bdR01qA+JTcL6fZvsr/MEogSK7dPw=,iv:fE1Pyg6FefiI5DdDOIqqmWqRl8uRGHnvn1IJ9DtRCac=,tag:wiuSmq8KUxakspR26vyxtA==,type:str]
    version: 3.13.3
