---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authelia
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.0.1
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ${APP}
spec:
  chartRef:
    kind: OCIRepository
    name: ${APP}
  interval: 1h
  values:
    controllers:
      *app :
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          labels:
            ingress.samoth.eu/vmagent: allow
            ingress.samoth.eu/envoy-internal: allow
            egress.samoth.eu/database: allow
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            seccompProfile: { type: "RuntimeDefault" }
        containers:
          app:
            image:
              repository: ghcr.io/authelia/authelia
              tag: 4.39.20
            env:
              X_AUTHELIA_CONFIG: /config/configuration.yaml
              X_AUTHELIA_CONFIG_FILTERS: template
              AUTHELIA_SERVER_ADDRESS: tcp://:80
              AUTHELIA_SERVER_DISABLE_HEALTHCHECK: "true"
              AUTHELIA_TELEMETRY_METRICS_ADDRESS: tcp://0.0.0.0:8080
              AUTHELIA_TELEMETRY_METRICS_ENABLED: "true"
              AUTHELIA_THEME: dark
              # VALKEY
              AUTHELIA_SESSION_REDIS_HOST:
                valueFrom:
                  secretKeyRef:
                    name: ${APP}-valkey-secret
                    key: hostname
              AUTHELIA_SESSION_REDIS_PORT:
                valueFrom:
                  secretKeyRef:
                    name: ${APP}-valkey-secret
                    key: port
              AUTHELIA_SESSION_REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: ${APP}-valkey-secret
                    key: password
              # POSTGRES
              AUTHELIA_STORAGE_POSTGRES_ADDRESS:
                valueFrom:
                  secretKeyRef:
                    name: postgres-user-${APP}
                    key: hostname
              AUTHELIA_STORAGE_POSTGRES_DATABASE:
                valueFrom:
                  secretKeyRef:
                    name: postgres-user-${APP}
                    key: database-name
              AUTHELIA_STORAGE_POSTGRES_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: postgres-user-${APP}
                    key: username
              AUTHELIA_STORAGE_POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: postgres-user-${APP}
                    key: password
            envFrom:
              - secretRef:
                  name: ${APP}-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 42Mi
              limits:
                memory: 42Mi
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      priorityClassName: security
      shareProcessNamespace: false
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: ${APP}
    service:
      *app :
        controller: ${APP}
        ports:
          http:
            port: *port
          metrics:
            port: 8080
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: metrics
    route:
      *app :
        hostnames:
          - "${APP}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: ${APP}
                port: http
    persistence:
      config:
        enabled: true
        type: configMap
        name: ${APP}-config
        globalMounts:
          - path: /config/configuration.yaml
            subPath: configuration.yaml
            readOnly: true
      secret-files:
        enabled: true
        type: secret
        name: ${APP}-secret
        globalMounts:
          - path: /config/secret
    serviceAccount:
      *app :
        enabled: false