apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:Md6kU1ehB0DrLhvYOkuYJLKECmbIor2MjNmLaEpOQxScNSwgW57g815jw2uEVhRelur8xTMioqsjsT27TV7tEQ==,iv:qpl6dQ4G4KYbq5mbR6kCYJpEufsKALC7N17s+urRVMk=,tag:QeT41efD83NKOg5vOmJuXw==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:ZqrgM/Hj+CvcX/9wEEN/3JajKmljE26fySsDg6JrUuLK20jkzHITvi0QqjS40UeIJO0MNJlEKf6S1u+xeKR3wQ==,iv:suWT8ACSxd3dbtyMYBj8Qy3tN4zQQtKNNql2x8XM2EY=,tag:czn1ReH6mbuiNOAxabtvPw==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:7raeZfOLs/mpWW5NR60VsgX3W06CXpaxDAGmcDKtYQXn3BxxttXsR+r4k0VLvhj2xF04HEyQwDld94cNi8lZ6Q==,iv:/qgdgdLp8QWA8a47r6ehSCikb2tiucs7VRpQnr4DhHc=,tag:RM+bqtPIEhOaEnwPECDavA==,type:str]
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:jLURFaaUe+VNA/gzw2Arn+iiZM/WI6fSffpReYk9HCyRvMy76nXrQyUzxJYOgvuDtZGwC5/xMzLY6o7MrIdaMA==,iv:RBIT9j+nZRWUDrjyafjUIbWoQEupiSh+gu/unJLbo4E=,tag:Bb7nS/n8RgL1RtUu7o+iLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY2ZXdG1LMUlFVUh3cHBS
            UW9wZE5sbldPWDFHZXIxWmtGUXpKRUdmMWhNCnQrOVNCbTI0RVdVajduUXpVdFFo
            d0QwNUZ5SW82MlpEYnlaYStVaWk3dXMKLS0tIG11R3M4REhiSEVlUjJMd0dGSjdI
            WkpBMDM1MklaOEc5S2VvMjI3dm1OcHMKMN9wKmMSNVnCP3ljlRDApQYntF7uY/jD
            DBr/1WpaAeVSxbzq2XbT+4eNsotG7rhFImPcBz23gpQqXF8LtLnysA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T13:30:10Z"
    mac: ENC[AES256_GCM,data:RQglJAqHAPXlRUP0UtvBfEIKgL5ubKa+5jEJG5mFeK/OSHprIQDk8I6li5FVyem68t8ivPeySczLV9/Jky5PFxtX4BcHF4U8iuDMoemIUCXMAWMJJErktLiBqxf1/30ADDFpRSZWaEfJ3mF1npB3bFHulT+8phKP5KvyOh2g21s=,iv:d1p/vDUteJ6T+KsynuDQGVktbe4J+EMAWIWdTO9ER4g=,tag:htKzQ22/sF59VHVwSuvrvQ==,type:str]
    version: 3.13.1
