network_conn_name: netplan-eth0
ipv4_addresses:
  - 192.168.0.2/24

ipv6_addresses:
  - fe80::2/64

hostname: "PiHoleGamma"
rpi_base_username: thomas
dococd_folder: ../docker/PiHoleGamma/
unattended_upgrade_reboot_time: 05:30