apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-webhook
type: Opaque
stringData:
  url: ENC[AES256_GCM,data:JPatiiek1E60/t+8VEnekgBqyV0OAfhtj0ab9aRatrin83mDgk0EdIk/R2IVHbpwT2GfmfBLYBlzkrNC/Ae36dPcZD4/LGFMxjXXOL2a8w/PjiLvg2aGbrjk3Zb914fQoTojiavFVlepn+XvMpBxXDpix9fu3q1Msw==,iv:4i31ktf5orVqSLm43zkD4Tzt4kh9vcPNAwXL15IkNow=,tag:kXL8zGXO19PvR1tBEPHc7A==,type:str]
sops:
  age:
    - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRjZGM21lMmNtN3RqSFU3
        dll6blZiYjJ2Qnh6M0E5Vk9wL2J2cTcwYVhrClVLQklVcThHUFB3QmJkdDJPeXpL
        TTZXNlpOcWRpVEMwNytCSDZXTTRNdDgKLS0tIFJleXVCc3VRZlFGK2k3cFhjNDNk
        RCtONjF6NVljelRONVcyQVJvRUExOEkKa7ho7k8bGrvMsNZtb9IKVZ8XP0F4MIsW
        9kHKFPJVH8odE3tLYEgZ7x8uPLjTLpDyaupqlA1gk83S67ubGq97cg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T14:13:01Z"
  mac: ENC[AES256_GCM,data:PF3eD1fZDxhmmx6MEPC115O5R7wy8UddrGv5hzz1H2agvC/TETqlqOxxkHzY+NAHkISR7+kaQuoc6P2fm1RpYHcvQg1i6c4ERGYghxgBNf7uRpJbMj6iZB9mYih4rVAgzfC+Dnww7IO2rfhM1xt2O9tSWaH2wphtOGKHNhZc82k=,iv:sgCYE/VyLu7uUkhOL3IsQ+AahgPNZj8tv9aE+SD2l14=,tag:RuR+pE6kRAY+iAmzJ7jnUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
