---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-sandbox

components:
  - ../../components/namespace
  - ../../components/sops

resources:
  - ./gitlab-runner/ks.yaml
