apiVersion: v1
kind: Secret
metadata:
  name: ${APP}
stringData:
  runner-token: ENC[AES256_GCM,data:9d3gRgvfz/3mfLDGUox7YdynfWCeo7fHyBii0KmkVv2VADwfTbJHNyDkGftXuS4X6lMcjiw20Zg=,iv:tRTohNvp39rRx+S1/gwf3MhIb7yUaxs0tIdbYtLz2Mo=,tag:2kHW3Drzi5bBMqAcyz+b6g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdmtyS1RlVEhJUVkvYTBt
        bDdiV25yK3ZXNHA0dWdxSURZbytYTkd3VzFzClFrUlJJQlFhcnRjdGlUd2c0Z0ww
        emd2OWFPejAvWUw1UVFMMHRLQjZhcGsKLS0tIDlsa200WWRKVCtvTER3Y3VuNi9R
        d3Q5TmltWXNZWHBVMmU3R3ZvMnhHdDQKyult0EBwXxa7tQLxq8TkwicLd7CilNUp
        cH4ywIYw0zvCgGd+3doz6mGLpaHZN8nIblQMigeFo2LtEqsFnf8Aug==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T19:07:56Z"
  mac: ENC[AES256_GCM,data:LEWi24Wi5yJtphgGfivHgCsjwTmkujGcPJNVFg0DeRJj/A1bu+9yBEoTeToe/ArWwTl+C2hFSiHgaGbEC6S/hyyPtnDIBQNhU80KmajWPYIAwNbFFA4a/15q0rNsUlb05oRbs5XLiQyXMRdMPfTXIJtBF2729YWYrnZjuO4wxYo=,iv:bDT1x81/bjmUDZ5tThzFMZFOH54F7up+zCVXtcJoec0=,tag:L00ldWYjJMAs6Shi+8Nalg==,type:str]
  version: 3.13.3
