apiVersion: v1
kind: Secret
metadata:
    name: ${APP}
stringData:
    runner-token: ENC[AES256_GCM,data:S2aso6d+AaMAHIPALNIOECW2O2BaU8eKFRjhQ4z9/1GzMIni5zXaB+9jXEY7AU/AN9ZYHmzqiRU=,iv:+N/hCZfkWTXyrFVHXUcH4P6WV9qKpEVdf20PV9ur6jQ=,tag:xL4OoeC0+xpIfdJSb30zJw==,type:str]
    runner-registration-token: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdmtyS1RlVEhJUVkvYTBt
            bDdiV25yK3ZXNHA0dWdxSURZbytYTkd3VzFzClFrUlJJQlFhcnRjdGlUd2c0Z0ww
            emd2OWFPejAvWUw1UVFMMHRLQjZhcGsKLS0tIDlsa200WWRKVCtvTER3Y3VuNi9R
            d3Q5TmltWXNZWHBVMmU3R3ZvMnhHdDQKyult0EBwXxa7tQLxq8TkwicLd7CilNUp
            cH4ywIYw0zvCgGd+3doz6mGLpaHZN8nIblQMigeFo2LtEqsFnf8Aug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T19:15:57Z"
    mac: ENC[AES256_GCM,data:JoGAsUDe48mC6iz89CcXe+A9XH3EnDUi1bhC7DXE5H5Gcc2/oiWfIKETBTKKXpdan20ieOWA89fO7u1yJ/D6Hlqb48GDa+qxq8A1KLDOx9ibe0L7IsA8zqbj15aSl9Sw2FPb2obPLHG5m80SmeSJcriYv269xQ82oUJ1yosF8QM=,iv:3frldtwJjqIBbQKMsW9SQGH5HaREBJBRtK3R7RyhVN8=,tag:7Lw9VmR3bxptJLLOgEtk1Q==,type:str]
    version: 3.13.3
