apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
stringData:
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:RdJhkI9eJ8PbMknrwCA=,iv:glrfyUHCusdsKMRuvTp8Ax5hYIE4ykLd03EtqrHwsS0=,tag:p0HP6HAk6qGwy37atm38ag==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:dBXCP30=,iv:kqN9TCY+Y/6ldP14VVxy4eMzhJvfFt393yqH0+dggh0=,tag:jUf3jPpPP28revucSY7Weg==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:xumQcuLVtbpy,iv:MCbgpA1KTFpWCmVsUQ2BTStvW1FIRfMyMviWLXlZVDE=,tag:P1bX/Xu9XHgmDUaAGCsfJA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:0tghEofGOmfjdaCpVc1HTXlZidkjeHmA/3Q33v2L1cDEZ2LA6961ijrgi64=,iv:sHgbQheDuiuC8RO6i/FArpPveDhQO1HrXRbpQ/QyK8c=,tag:4XV9oBnArNq0oL7nCTvlEw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ZTJmEYH7wMiG7a64edk61xHssaET8JhnlzvfRzD36nkPERLFpNn61USBt1I=,iv:WBXGWrb/UyhNaXqy0zENV5q/3XnRPRMyrsGdUr4k1Z0=,tag:ouL4RNF0XSsRMR8ldE2ftA==,type:str]
sops:
    age:
        - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRTBHY0pZZEU2Y3JKMVpi
            amxrc2l5ejZ4Z2JWZkZwUkdwa0Eyb1FXV3lJCnZuTWFFQ1JNL0lvdnZtdElxWHpV
            U2I1emYxdWNIREpCRzdCZmlCeU9QNkUKLS0tIGFwazJwME51aVlZWUo1OFBNSnMx
            TTRBT20zanhtOEZOa2FKa3k2YlVZQkEKm1ToDFReNmgdeqPMQFiMi+2OGTfrhPo8
            4rlw8Hnza6E4zDSZ1x8CHfOQbXl8BZcta/vssKwv4iGYtiYT//cU+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T14:35:07Z"
    mac: ENC[AES256_GCM,data:6KVU5aEb5PDMsBhN9CDPn8Kirk36Ma2BBc6r7N6dhm49BTvtiMnA6IoSLhk9WXdkl05/Z/d3Z9eGoKJ3XiJt8wLyi+WwaZg9XPyIZiIE1lupqKM2Qbvjez4eAhZX0BIHi45Kmw0E5BbvK67R6/DNIGtFu4THY/DkhIe95pgDliI=,iv:eg6Z9PzGuLlORlPTm0LXbjeh9VhXP+t53DS7fDiiGTY=,tag:sjVmiwLHj+ytHnhho39png==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
