apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:uFHOn/AhJ/Z3ULBVjDx6dU9ZxX//yL0nWuzy/RpyEDl1UBCG7POy6ZEf535i3LYpyFddovlxcLp0e+Hsi007ig==,iv:Lidrl7Hj7kfihjbDJNYpfGtph9vssvhdOu1LaLsipkA=,tag:Km8ak42R0NwSsCFESXEvJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY2ZXdG1LMUlFVUh3cHBS
            UW9wZE5sbldPWDFHZXIxWmtGUXpKRUdmMWhNCnQrOVNCbTI0RVdVajduUXpVdFFo
            d0QwNUZ5SW82MlpEYnlaYStVaWk3dXMKLS0tIG11R3M4REhiSEVlUjJMd0dGSjdI
            WkpBMDM1MklaOEc5S2VvMjI3dm1OcHMKMN9wKmMSNVnCP3ljlRDApQYntF7uY/jD
            DBr/1WpaAeVSxbzq2XbT+4eNsotG7rhFImPcBz23gpQqXF8LtLnysA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T15:44:41Z"
    mac: ENC[AES256_GCM,data:L0pHIlZm/nLCkm9TssE6TfMxCjLh9KhiOvREpjsgrTBTjydFQOBN8LvW5oSvE6Nsr/eBnjk6AxegJSZW66bDG6NDAy4xSgDyiVuSqCI+M6whpWtiPLvX0xEsgG6fTP5WF/KxHXFpgEhy8Fq0QvbnfXImWsJ9r0Lg5+JmveJGwS0=,iv:thiR+3XvIwrrqEhQNlk9tndnE2jtbBasj+v8orOThfw=,tag:jm9M5MIiMRL0GQKYr9kwkg==,type:str]
    version: 3.13.0
