---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-valkey-secret
spec:
  refreshPolicy: CreatedOnce
  target:
    name: ${APP}-valkey-secret
    template:
      data:
        hostname: "{APP}-valkey"
        password: "{{ .password }}"
        port: "6379"
        url: "redis://:{{ urlquery .password }}@${APP}-valkey:6379"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: ${APP}-valkey-password-generator