---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${APP}-valkey
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.9.4
  url: oci://ghcr.io/valkey-io/valkey-helm/valkey
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ${APP}-valkey
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    image:
      registry: ghcr.io
      repository: valkey-io/valkey
      tag: 9.0.3-alpine
    
    workloadAnnotations:
      reloader.stakater.com/auto: "true"
    
    podLabels:
      ingress.samoth.eu/vmagent: allow
    
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 512Mi
    
    auth:
      enabled: true
      usersExistingSecret: ${APP}-valkey-secret
      aclUsers:
        default:
          permissions: "~* &* +@all"
          passwordKey: "password"
