# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: ${APP}-valkey
spec:
  description: "Allow the app to talk to valkey"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: ${INSTANCE_NAME:=${APP}-valkey}
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: ${INSTANCE_NAME:=${APP}}
  egress: 
    - {}
