---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kopiur
spec:
  components:
    - ../../../../components/app-network-policy
  interval: 1h
  path: ./clusters/k4/kubernetes/apps/system/kopiur/app
  targetNamespace: &namespace system
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      NAMESPACE: *namespace
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kopiur-repository
spec:
  dependsOn:
    - name: kopiur
  interval: 1h
  path: ./clusters/k4/kubernetes/apps/system/kopiur/repository
  targetNamespace: &namespace system
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: ClusterRepository
      name: garage
  healthCheckExprs:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: ClusterRepository
      current: status.phase == 'Ready'
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      NAMESPACE: *namespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
