apiVersion: v1
kind: Secret
metadata:
    name: qui-oidc-secret
stringData:
    client-id: ENC[AES256_GCM,data:hN9Z,iv:Y9pR8lvgILrdxhFIAkE43/sX559ADCmXFSMLpMzpww0=,tag:DkyBLuFB2xvl6NvVsai5cg==,type:str]
    client-secret: ENC[AES256_GCM,data:5iU5lLlT05uF44TptJHu4TdTpzxrKl0wkQbD951Tuc/WkXEQEtBCSgmHlc1vro1yhqKYbm1klBMaOulrjLn+pg==,iv:Mmzneb/EreUvKp2VxTCoZMHSfqvGejwSrnEzcalTmk4=,tag:9Skrm1+qwKOnXEBCPT/gYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeWM5M1VBMC9QUkt0cHZu
            K3dKRXQ5TElHbzRudnRsRU9Takx3bnFUNGtRClF1RkhNcVdZaUhJMmR6RDJPN21t
            dUUyc0hBQmdid3ZVZkJGOWhYSXc1bE0KLS0tIEJ6ajJWb29kOW1kSXd6WHVvbmFI
            dW96RWFUVGZzM2pnQ1d2Mmx1MVY5YlUKvF/ha4msksqdcDbc91Y3DLzN44XF3vev
            hBC6pyyTPGDN5SNRwOxQRb4wshd1elBUvppiM4b1qCLWEHBn+334JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T15:53:22Z"
    mac: ENC[AES256_GCM,data:GbifwpP0i0RRdi8/70sqRlRgKv5ZlS/1rrRq97XclLek5hl+QcHUJVq9REwLdJ9cLKVDxrOOQjbRt+hOyqY6Kaio4foRCKDfyOSqINsKDPXHqToZzU+7y8wKu1fWZyIqRIGmz/JHTwVcjgBltFU8Ded8Bs99dhwryD1SCLM1sNY=,iv:qfcM/RuDPvAZCSfu99HCNx9dIydNxaI+HLPSLCndToY=,tag:Yl/2wNsi+OYACoTgcZ9b0g==,type:str]
    version: 3.13.1
