apiVersion: v1
kind: Secret
metadata:
  name: qui-oidc-secret
stringData:
  client-id: ENC[AES256_GCM,data:3VaQ63PY1OEOkDT3rqEtWZN21A0MXlA2xLk3bYD05wAqvdzewjWt5g==,iv:MbIPv+cEodNqeSIufCsBXe2tBf58PKjSPcQfKxdbfbk=,tag:udHKMw6jA4QQk19gfF+3+g==,type:str]
  client-secret: ENC[AES256_GCM,data:tQjbP2D8xT7XSiCsCGGYb1KgC7wrmIj2zYnbgc1QIABWVVlHF+jbYH5r0eWVW0LIvz9pnqe3nRvgnnCF+qNP8Be5oZ0ihRaN1OXbJDHkK9hdlbg/oA97N8yl4jPaxqVizwejbGtlu3u5eAB3y/ry2GV5A5h+Zs9KhWqCDycaaV0=,iv:KGSpUDZpZLiol0+zDKU4NbZlfzr5FXD79sH2hwUlylI=,tag:oZheETfXY7SwJUMLLJMvEw==,type:str]
sops:
  age:
    - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeWM5M1VBMC9QUkt0cHZu
        K3dKRXQ5TElHbzRudnRsRU9Takx3bnFUNGtRClF1RkhNcVdZaUhJMmR6RDJPN21t
        dUUyc0hBQmdid3ZVZkJGOWhYSXc1bE0KLS0tIEJ6ajJWb29kOW1kSXd6WHVvbmFI
        dW96RWFUVGZzM2pnQ1d2Mmx1MVY5YlUKvF/ha4msksqdcDbc91Y3DLzN44XF3vev
        hBC6pyyTPGDN5SNRwOxQRb4wshd1elBUvppiM4b1qCLWEHBn+334JQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-21T18:37:24Z"
  mac: ENC[AES256_GCM,data:cCPNK+1+qJsvAuwDuBTYirTlQncRp7niDeAm7YJUv+G3LZoh/HA52gMFxgkW4c11ljn9MUiRKNs1m795dB2NlGQisr9mH/i0Fkz19NWImJ8kL5BI0ovfqWt79oYcXVO4bMnnGj60oDD6KZYsrD2pojkbFqfMwJa5oLR9oAT1ljA=,iv:CZPdokjI8o4Xz5Ne3wmPaWyWe5FVDaGdfvxHp1l2qcY=,tag:tN9qi/ndpNC+/pwnB8GVmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
