# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-kanidm-oidc
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: SecretStore
    name: ${APP}-kubernetes
  target:
    name: ${APP}-kanidm-oidc
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
              "APPS": [
                {
                  "provider_id": "kanidm",
                  "name": "Kandim",
                  "client_id": "{{ .CLIENT_ID }}",
                  "secret": "{{ .CLIENT_SECRET }}",
                  "settings": {
                    "server_url": "https://idm.${SECRET_DOMAIN}/oauth2/openid/paperless",
                    "claims": {"username": "email"},
                    "oauth_pkce_enabled": true,
                    "fetch_userinfo": true
                  }
                }
              ],
              "SCOPE": ["openid", "profile", "email"]
            }
          }
  data:
    - secretKey: CLIENT_ID
      remoteRef:
        key: ${APP}-kanidm-oauth2-credentials
        property: CLIENT_ID
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: ${APP}-kanidm-oauth2-credentials
        property: CLIENT_SECRET