---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: paperless
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      paperless:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          labels:
            ingress.samoth.eu/envoy-internal: allow
            egress.samoth.eu/envoy-internal: allow
            egress.samoth.eu/database: allow
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.20.15
            env:
              # Configure application
              PAPERLESS_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_SECRET_KEY
              PAPERLESS_URL: https://paperless.${SECRET_DOMAIN}
              PAPERLESS_PORT: "8000"
              PAPERLESS_TIME_ZONE: "Europe/Paris"
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_TASK_WORKERS: "2"
              PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
              # Configure folders
              PAPERLESS_CONSUMPTION_DIR: /data/nas/incoming
              PAPERLESS_DATA_DIR: /data/local/data
              PAPERLESS_EXPORT_DIR: /data/nas/export
              PAPERLESS_MEDIA_ROOT: /data/local/media
              # Configure folder importer
              PAPERLESS_CONSUMER_POLLING: "60"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              # Configure OCR
              PAPERLESS_OCR_LANGUAGES: fra
              PAPERLESS_OCR_LANGUAGE: fra
              # Configure redis integration
              PAPERLESS_REDIS:
                valueFrom:
                  secretKeyRef:
                    name: paperless-valkey-secret
                    key: url
              # Configure postgres
              PAPERLESS_DBHOST:
                valueFrom:
                  secretKeyRef:
                    name: postgres-user-paperless
                    key: hostname
              PAPERLESS_DBNAME:
                valueFrom:
                  secretKeyRef:
                    name: postgres-user-paperless
                    key: database-name
              PAPERLESS_DBUSER:
                valueFrom:
                  secretKeyRef:
                    name: postgres-user-paperless
                    key: username
              PAPERLESS_DBPASS:
                valueFrom:
                  secretKeyRef:
                    name: postgres-user-paperless
                    key: password
              PAPERLESS_DBSSLMODE: require
              # Configure user permissions
              USERMAP_UID: "2000" # truenas:k4
              USERMAP_GID: "2000" # truenas:k4
              # Configure SSO
              PAPERLESS_DISABLE_REGULAR_LOGIN: true
              PAPERLESS_REDIRECT_LOGIN_TO_SSO: true
              PAPERLESS_SOCIALACCOUNT_PROVIDERS:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_SOCIALACCOUNT_PROVIDERS
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 25m
                memory: 2Gi
              limits:
                memory: 6Gi
    service:
      app:
        ports:
          http:
            port: 8000
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: http
    persistence:
      data:
        existingClaim: paperless
        advancedMounts:
          paperless:
            app:
              - path: /data/local
      nas:
        type: nfs
        path: /mnt/ThePool/Apps/Paperless
        server: ${SECRET_TRUENAS_IP}
        advancedMounts:
          paperless:
            app:
              - path: /data/nas