apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:8uzBE2HSnwcLxb5CwyTxVE8G4rwQvMCEHjvJaOucA3J+V5cGcbo/udeN9QvpHLY0oVbwaS+7X0BGREHgBhTxhg==,iv:Hf6SgcQWAk/lgC0vbns3tjpS5ajhq8YyNBtenEt8IJc=,tag:mpNkFEDIMvp6mlABpYtyFg==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:ii0xvxJNwltgL/mgb1E0ppXWNJoVg135M2r6WuGcjxFlAZo0jgZIweLwU5svtiFKpSVsM+jAR33AXe5zGsmsdkhX8EQlvUdaP36BaUMuGg1CDwi3h4ecUi9qvyVwtpjFO6x9Wb++kuZfEaRPqtgKb7vdXSQrdk2CzjZoHGjtLA9xrntF5U9PITjfRS2Q8SGcUtaGmfABOGzAAH9xqVcIR6Avi28EPqs0nKzr4D1lP0pTAIKSKo1z1mn/+BwBwKgySzjtWHGfuupiSekM2QiaipIxyKRD4v96a7Qd10NkAl+qWhTL+ONbhvwf282/Z50/cEgJ4k756HdtYPBOU2YioYpyL6tPTOIdSqwbzCRKVCypTVz7lFZ8rHZHr6s1QyEbxSyFkmRjzsN62AJ43OlziYl2Qr2fkiLWAWQwjK3xF77QtHCfxeRP5cggYkCAWIzyGkEEvmcik/wFqRTyZaDMCY2FHk5HwW7o+pXSlUb+s1JW1Vmn+bcE8kCHcPd+2h43fx9xrqVLvopJANLhEZa6hFnAxKxd/22IWCn8V2OL33zMsribyO3F9mL7Aooyv03QfBmnLwxq1mDVzGA+wt5r35k2haAYzzlfN+02wORo9rVijYqODNLa3Cs2upRIe9t4Qg9jHSbu1JGYf5G2gr/QrhHAse6yc//nKjZfuNKHWgkbmwB4BM/sIaVj/gjy6oq/p4EfT7PRRHEPHPWsSLnFBpqxy3f0MhmOmKDglTbNHK3D,iv:Eb4Jx9DPCOxOqHNabftxzabDeiqrQOYIhKy2HR4FdnI=,tag:tMzqZXg3a+2lsFnXwUwEPQ==,type:str]
sops:
    age:
        - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY2ZXdG1LMUlFVUh3cHBS
            UW9wZE5sbldPWDFHZXIxWmtGUXpKRUdmMWhNCnQrOVNCbTI0RVdVajduUXpVdFFo
            d0QwNUZ5SW82MlpEYnlaYStVaWk3dXMKLS0tIG11R3M4REhiSEVlUjJMd0dGSjdI
            WkpBMDM1MklaOEc5S2VvMjI3dm1OcHMKMN9wKmMSNVnCP3ljlRDApQYntF7uY/jD
            DBr/1WpaAeVSxbzq2XbT+4eNsotG7rhFImPcBz23gpQqXF8LtLnysA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T13:57:42Z"
    mac: ENC[AES256_GCM,data:0zpvS1l7NmGyKaP/BFiYE+Strxb5JqRplh8D6YrbHBD69JK/Egf8kkjNvaAP6Wl224ItGmb+1bpzhIzpjaXmKflRNmlj6HH5DyDezo3UkESgH3fBieYppCq5Hc2LnanDya7sp/i6GKZwJqMnZviqJnk/60TAU6sih9S9VVzmHsY=,iv:bs9T9NuE+T2wvMLSZj8cM6SzmYQD7xd6UCJN7rivb7I=,tag:SrICtF5o0H0i8VTXSV/qwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
