---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/sops
  - ../../components/namespace-isolated

resources:
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr-anime/ks.yaml
