# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/kyverno.io/policy_v1.json
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: pss-baseline-special
  annotations:
    policies.kyverno.io/title: Baseline Pod Security Standards
    policies.kyverno.io/category: Pod Security, EKS Best Practices
    policies.kyverno.io/severity: high
    kyverno.io/kyverno-version: 1.8.0
    policies.kyverno.io/minversion: 1.8.0
    kyverno.io/kubernetes-version: "1.24"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The baseline profile of the Pod Security Standards is a collection of the
      most basic and important steps that can be taken to secure Pods. Beginning
      with Kyverno 1.8, an entire profile may be assigned to the cluster through a
      single rule. This policy configures the baseline profile through the latest
      version of the Pod Security Standards cluster wide.
spec:
  background: true
  rules:
    - name: pss-baseline-rule
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE
                - UPDATE
      validate:
        allowExistingViolations: false
        failureAction: Enforce
        podSecurity:
          level: baseline
          version: latest
          exclude:
            - controlName: HostPath Volumes
              restrictedField: spec.volumes[*].hostPath
              values:
                - /var/mnt/hdd1
            - controlName: Capabilities
              images:
                - ghcr.io/qdm12/gluetun:*
              restrictedField: spec.initContainers[*].securityContext.capabilities.add[*]
              values:
                - NET_ADMIN