apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    TWITCH_CLIENT_ID: ENC[AES256_GCM,data:qqwY8LgCQhMPFAYJlFc5sc89zs7mABefzgakO+Rh,iv:XYNF7cbKM9BaBeAjtYxrMFM638bXZNWnFnNcLin23/0=,tag:kFdht7Cu6v30cxiNBhebHA==,type:str]
    TWITCH_CLIENT_SECRET: ENC[AES256_GCM,data:YB/qEgOKvtbulZqXu6SxoaCFeF4zvIO6MJJT1F0n,iv:hOfdTehoMDqV5aopeWuba47n57er9wlCSwhTxYKoaec=,tag:u1XUZpsAFyb2CDniTaNiTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY2ZXdG1LMUlFVUh3cHBS
            UW9wZE5sbldPWDFHZXIxWmtGUXpKRUdmMWhNCnQrOVNCbTI0RVdVajduUXpVdFFo
            d0QwNUZ5SW82MlpEYnlaYStVaWk3dXMKLS0tIG11R3M4REhiSEVlUjJMd0dGSjdI
            WkpBMDM1MklaOEc5S2VvMjI3dm1OcHMKMN9wKmMSNVnCP3ljlRDApQYntF7uY/jD
            DBr/1WpaAeVSxbzq2XbT+4eNsotG7rhFImPcBz23gpQqXF8LtLnysA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:37:45Z"
    mac: ENC[AES256_GCM,data:QVObzTYXMjwCn/6qO+1Y9rd0piAGRpY/6aMGf0yMJGM6R/kvvkN1eDtO7c73cSggp3X048/r72O6zMfaU9MT+Vm7FTl9aeNMkoStUp2l7FnuzimHihLPVZzHse2IaRqjkZW6CXiWgv9wMh8sSA9qftRrsfvm5CUBeskeLZTgWA8=,iv:+kxHeLQcc/NN7oLBJVaO63k9/LbksVNmQz3+ncnHZqs=,tag:E4lZ6XHf9Q0BoorQ36YPMA==,type:str]
    version: 3.13.3
