---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: spegel
spec:
  interval: 1h
  url: oci://ghcr.io/spegel-org/helm-charts/spegel
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.6.0
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: spegel
  values:
    grafanaDashboard:
      enabled: true
    service:
      registry:
        hostPort: 29999
    serviceMonitor:
      enabled: true
    spegel:
      containerdSock: /run/containerd/containerd.sock
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
      resolveLatestTag: false
    # Graceful Helmfile to HelmRelease takeover
    commonLabels:
      helm.toolkit.fluxcd.io/name: spegel
      helm.toolkit.fluxcd.io/namespace: kube-system

