---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./check-serviceaccount-secrets.yaml
  - ./deny-ingress.yaml
  - ./deny-secret-serviceaccount-token-type.yaml
  - ./pss-baseline.yaml
  - ./pss-restricted.yaml
  - ./restrict-serviceaccount-automount-sa-token.yaml
