---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${APP}
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.1.0
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  chartRef:
    kind: OCIRepository
    name: ${APP}
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    controllers:
      karakeep:
        forceRename: karakeep
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          labels:
            app.kubernetes.io/component: application
            egress.samoth.eu/internet-http: allow
        containers:
          app:
            image:
              repository: ghcr.io/karakeep-app/karakeep
              tag: 0.33.2
            env:
              BROWSER_WEB_URL: http://karakeep-chrome.selfhosted.svc.cluster.local:9222
              CRAWLER_DOWNLOAD_BANNER_IMAGE: true
              CRAWLER_ENABLE_ADBLOCKER: true
              CRAWLER_STORE_SCREENSHOT: true
              DATA_DIR: /data
              DISABLE_SIGNUPS: true
              MEILI_ADDR: http://karakeep-meilisearch.selfhosted.svc.cluster.local:7700
              MEILI_MASTER_KEY:
                valueFrom:
                  secretKeyRef:
                    name: karakeep-secret
                    key: MEILISEARCH_MASTER_KEY
              NEXTAUTH_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: karakeep-secret
                    key: ENCRYPTION_KEY
              NEXTAUTH_URL: https://karakeep.${SECRET_DOMAIN}
              DISABLE_NEW_RELEASE_CHECK: true
              COREPACK_INTEGRITY_KEYS: 0
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
      chrome:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          labels:
            app.kubernetes.io/component: chrome
            egress.samoth.eu/internet-http: allow
        containers:
          app:
            image:
              repository: docker.io/zenika/alpine-chrome
              tag: "124"
            command:
              - chromium-browser
            args:
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            securityContext:
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
      meilisearch:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          labels:
            app.kubernetes.io/component: meilisearch
            egress.samoth.eu: deny
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - karakeep
                      - key: app.kubernetes.io/controller
                        operator: In
                        values:
                          - karakeep
                  topologyKey: kubernetes.io/hostname
        containers:
          app:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.53.1@sha256:8d6643d86d71fad6ad3cba92cde7ccfce9e4d6c384bda67598eb553571c32431
            args:
              - /bin/meilisearch
              - --upgrade-db
            env:
              MEILI_NO_ANALYTICS: true
              MEILI_MASTER_KEY:
                valueFrom:
                  secretKeyRef:
                    name: karakeep-secret
                    key: MEILISEARCH_MASTER_KEY
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
    persistence:
      data:
        existingClaim: karakeep
        advancedMounts:
          karakeep:
            app:
              - path: /data
                subPath: karakeep
          meilisearch:
            app:
              - path: /meili_data
                subPath: meilisearch
    route:
      app:
        hostnames: ["${APP}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: http
    service:
      app:
        controller: karakeep
        forceRename: karakeep
        ports:
          http:
            port: 3000
        primary: true
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700