apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-secret
stringData:
  encryption_key: ENC[AES256_GCM,data:QVY4o1KGraYkjNyQ5dm0niBI8k3qzujXv/7yLgM4SMCMYd/BVKuAAwH2aFa70/tcFjfhBHJ0WqP7i36Jk5qeWQ==,iv:ax0IBLAoLS0XEZmAlkSIHeCvlBjgWwsePZb8ICfDj6U=,tag:w0MGtU4fCZx8P9+jQCTj0A==,type:str]
  meilisearch_master_key: ENC[AES256_GCM,data:9QaTCaoT/UZkmk5aNFuiwGB5xqxCdTFeYgrauif++fmVyXThqwoh9qRIOgapsdi3al3/XIsICt72IXyYWP/uQA==,iv:nujXqLiRl+gzgk0XQPZlBpvWzrpC6z6keGHsDavj928=,tag:+SPMlAhVstCmVSjcvkLxlA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaS3BKLzV0YWwrL1VyK2hW
        R1Q0dWQ1QTFsWXZUeVhGWEhZNXZzT05OVERNCkN6aDFwK05GNjRWQUxTS0pFOWYx
        QzdPQ2M4elJHaytiTmlJbjNIUEE3aTgKLS0tIHkyNElxZGN6L2dLYk04ajVub3k1
        ay9iQUlMY2JZb1gvbytiTWJHR2FyL1UKsGMe8rXoX1399KkOvU0yaflzHhUpkNB6
        5/GrZT22i4XLg1q7nzOSF58uZ77+2S6O7E7RFDVJgWowiWQ4I/RUPQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-01T19:46:58Z"
  mac: ENC[AES256_GCM,data:hUDWdaC3JRHHcWYnzCqRkvpG7kwHzgKOxbtB4q/GNVsGFZrTIy8K19PKiz1nD+I0rO+8kF9nk//etsszkmbzYdHm3vIBKDc8SHvjOMcJp8R4EyNA6iNnZ+AqV/FsKP6CgIjNoOIVex+eL9X5qyWLWShHcJ18/cfOZsWs69ZLORw=,iv:issEQpL000yD44bp5w59kZd5m8tIOTmlV4Br76/xmTk=,tag:lH1/NII3EW041iksD3VHAQ==,type:str]
  version: 3.13.3
