---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

components:
  - ../../components/sops
  - ../../components/namespace

resources:
  - ./policy.yaml
  - ./forgejo/ks.yaml
  - ./forgejo-runner/ks.yaml
  # - ./gitlab/ks.yaml
