---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  labels:
    ingress.samoth.eu/vmagent: allow
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie

  storage:
    storageClass: miroir-local
    size: 20G

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  bootstrap:
    recovery:
      source: &src source

  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: &store garage-store

  enablePDB: false

  externalClusters:
    - name: *src
      plugin:
        name: *plugin
        parameters:
          barmanObjectName: *store
          serverName: postgres

  postgresql:
    parameters:
      shared_buffers: "128MB" # should be 1/4 of memory request
    pg_hba:
      - hostssl all all all scram-sha-256

  managed:
    roles:
      # This user may be used for disaster recovery
      - name: app
        login: true
        superuser: true
        ensure: present
    services:
      disabledDefaultServices: ["ro", "r"]
  
  resources:
    requests:
      cpu: 150m
      memory: 512Mi
    limits:
      memory: 2Gi