---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./netpol.yaml
  - ./objectstore.yaml
  # No app uses it
  # - ./pooler-session-rw.yaml
  - ./pooler-transaction-rw.yaml
  - ./prometheusrule.yaml
  - ./scheduledbackup.yaml
  - ./secret.sops.yaml
  - ./tcproute.yaml
  - ./vmpodscrape.yaml