apiVersion: v1
kind: Secret
metadata:
    name: k4-cnpg
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:HLS25QdUqjkHNWQjhvS3n2NMebQenXI0MZM=,iv:S+B3hTqD00ef5e6CpydhTCAF4rXBMQMCwF2Pge7k8TY=,tag:Ev43TOX4FfQgEUU6rUYaRw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:l5mXBJ50POT6p/KCqpgV4Vag4Cb/nUKIgT8JiDwslTvK9KbjQZfLMS3e9GUMIO0jCigrwbRiKRaUzLs9DAKXGA==,iv:lY+asfBB/WvYuzuVcnFUeBtiokh+eD0Dk0pycftkrbU=,tag:3N0fznvZWoSStms2E5L7gg==,type:str]
    REGION: ENC[AES256_GCM,data:j/3QXkAn,iv:WCRqDybolT0yJ5QmBiZs+j6m8EDBjUmK/D2eWZE1+Y4=,tag:tl7i9Natltb4/Bcz3KoyEQ==,type:str]
sops:
    age:
        - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU28xeVV1cjlPM0hySXNl
            V3V4V21KcVlvYzNJbHMxbmJscEM4bnpNSDFJCk9OQzZLVGlaWXVNbU5TYmcySUhw
            cXN6VlNHTWpCNnUzMkpZcHlqUWlDNE0KLS0tIEFDT2VBM1JscTBiYVJpVnJobEtm
            ckMrcmFjaUh4RUJ6bVpaendNQWVqMXcK/MsBwX8Hdw+KjLcKWqtjoKx86YTZyvVz
            pRsWrZXWF94srYiuQM+i0gRTdSu7ANJQEJDjvtFN17epv9NYWQe37w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T17:48:13Z"
    mac: ENC[AES256_GCM,data:Mv6tuGyfB7Y/eRExjkgfv11aL2tyUgrY9XOgvnImC801NJeYNs29ipoPsgQmPdBaTOhT2ZKWOVXQhZyiRzgeiGOrSmnMoJXYjNWA/2CG9wm96v1VVVfAZJn3rg88/HqEtA+U4rRml5W/79fmFGRZ9vibrqyyJl/JKhLJFVuyOms=,iv:wYpCuZxoE5d/C5LutY5C4tTbkshRj2GDWwn+DjIWaOY=,tag:Fha4lE2AWRbCSxp1UmnDBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
