apiVersion: v1
kind: Secret
metadata:
    name: k4-cnpg
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:4WBDZqce1jgE1eTSJD3kl1q4FaoT9NBx93U=,iv:DqUiO1zGkTI3pPrB/XM3Z0CDVASgn+ka3Aj6CieEUIY=,tag:z2mwoPVHF3hsthvH+g82+Q==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:lMW8Az4I890wIShJLMCX8B7OZAvAdPnbDNSl8CxDlDLiuzetcnwS9oyNnICbPWwNPd0MO9sIE4X/d3QdFvVAsw==,iv:LntGmL5C9rGSF6J8+hx42KhIYNGbT3+PCwoVYz5Bc8Q=,tag:N3pOuZH4StWbg4GLSlV44Q==,type:str]
sops:
    age:
        - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU28xeVV1cjlPM0hySXNl
            V3V4V21KcVlvYzNJbHMxbmJscEM4bnpNSDFJCk9OQzZLVGlaWXVNbU5TYmcySUhw
            cXN6VlNHTWpCNnUzMkpZcHlqUWlDNE0KLS0tIEFDT2VBM1JscTBiYVJpVnJobEtm
            ckMrcmFjaUh4RUJ6bVpaendNQWVqMXcK/MsBwX8Hdw+KjLcKWqtjoKx86YTZyvVz
            pRsWrZXWF94srYiuQM+i0gRTdSu7ANJQEJDjvtFN17epv9NYWQe37w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T12:36:24Z"
    mac: ENC[AES256_GCM,data:Hy2CXn2+lvFUwjSIr0aY9/U/nzqPZaZw+w/rrYzhnJp53I8ygynMQBIswSb7IyjWZDosdzLj/nBmM4nzObn1l7y7Q98UAANcq2PpmXq8Cz3JyJ55X3+B5YT3C1k30dYN/yApovFu/eqwnXvP4W7NRUKpx+YXr3MaooII/d+CApM=,iv:tliqre0TA/pAiuMPfz6cFGybaMIEr8QbFy6mrLsDJJw=,tag:+Qi/KNPAh2mHwTbxbtLErw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
