# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/operator.victoriametrics.com/vmpodscrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: postgres
spec:
  podMetricsEndpoints:
    - port: metrics
      scheme: http
  selector:
    matchLabels:
      cnpg.io/cluster: postgres
