apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    api-key: ENC[AES256_GCM,data:NZR+ChQR4/TyOH0Di8GuLqlGR7USCgN9d0fe40Qz4ju2s6WH054brNqOFnvsRLR7bt0raKTq4nz4tKnrgrsHiA==,iv:AK8iTxhL2p9rPzvKZqZsZX/Wco7yMtE5Ni+2TI+L4n4=,tag:XqHKZOCxRotCMcROrvXJvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeWM5M1VBMC9QUkt0cHZu
            K3dKRXQ5TElHbzRudnRsRU9Takx3bnFUNGtRClF1RkhNcVdZaUhJMmR6RDJPN21t
            dUUyc0hBQmdid3ZVZkJGOWhYSXc1bE0KLS0tIEJ6ajJWb29kOW1kSXd6WHVvbmFI
            dW96RWFUVGZzM2pnQ1d2Mmx1MVY5YlUKvF/ha4msksqdcDbc91Y3DLzN44XF3vev
            hBC6pyyTPGDN5SNRwOxQRb4wshd1elBUvppiM4b1qCLWEHBn+334JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T17:57:36Z"
    mac: ENC[AES256_GCM,data:/IdoI3L1bfuBSPwTF6VseLT3cGt8hs5Tj0rqFigPQFNwhO6aIENq4VLMHVSAoIsvj0cqZs8Z8JqEOhWg3wAfJ4jvw1idgBYm/o+UN7hhBl8pzVxRDNmM+aqOPqQMhQLu0RWvg+HGtjlhf2FAuRnYlbny4SE8sC20Fdj7YQK3L8w=,iv:7pAmvvU+Ur6dK3nWJk7etegbutKPp2oW6060hDKD+QY=,tag:+2+sd+5z9kPWGuY0xrA1oQ==,type:str]
    version: 3.13.1
