apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    api-key: ENC[AES256_GCM,data:NZR+ChQR4/TyOH0Di8GuLqlGR7USCgN9d0fe40Qz4ju2s6WH054brNqOFnvsRLR7bt0raKTq4nz4tKnrgrsHiA==,iv:AK8iTxhL2p9rPzvKZqZsZX/Wco7yMtE5Ni+2TI+L4n4=,tag:XqHKZOCxRotCMcROrvXJvA==,type:str]
    client-id: ENC[AES256_GCM,data:RTQlKxLBppnMm4DGHWFBp44+L9Iu+oxxuh006P5osxhZGV/ms6osNQ==,iv:I0p7wAUcbzhMbRkZKpvbHqMwObWPTJ5euc/aXM6tRoM=,tag:7ZMttvjvQsVurmmTz4kCeA==,type:str]
    client-secret: ENC[AES256_GCM,data:dWcikL2LLBwNsI5wlesPjEew285HWnKqRxorJ1OuU1IsQbXbl24xVMelnpbwaoig5BZQI2QlhEjJ2tecI5iqODO9l9yp3x003rU1W1eVleYpNtRNTTzpWcVHN5St6MblcTXsfjsqOvDS0TmKOoTWfav6ngkRrX5C1j16RrPR1QU=,iv:7fP4IIG5i9s69f/Ri6rdLZgau0k9wzpb5itqfd25XMU=,tag:/ND1w+miBwP77Q/x0Gjlgg==,type:str]
sops:
    age:
        - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeWM5M1VBMC9QUkt0cHZu
            K3dKRXQ5TElHbzRudnRsRU9Takx3bnFUNGtRClF1RkhNcVdZaUhJMmR6RDJPN21t
            dUUyc0hBQmdid3ZVZkJGOWhYSXc1bE0KLS0tIEJ6ajJWb29kOW1kSXd6WHVvbmFI
            dW96RWFUVGZzM2pnQ1d2Mmx1MVY5YlUKvF/ha4msksqdcDbc91Y3DLzN44XF3vev
            hBC6pyyTPGDN5SNRwOxQRb4wshd1elBUvppiM4b1qCLWEHBn+334JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T19:32:57Z"
    mac: ENC[AES256_GCM,data:OGJvDmRLiEWPiz41MaITCi+dfWX0bsJS5Bvcq7gWTqLB76rz4uW5tJ6vjSJEqvg8uUH20SLLxHhjGrnhJa0kiP6fvz/mxn0Ra5ggXOBAoVE5jRnPMZjifdGDkLZMR9+vl0KLWWmhRh/C3+9HkRZ+amsmc0SDhO3sAS/H78vZ1wo=,iv:xZ5O+nvmzzAukZxEP+XmCYB4wKBSPN01kFLN0WN7Mrw=,tag:yMEED9FSrB8G+YBo7GzS6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
