---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2026.2.2
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    global:
      podLabels:
        ingress.samoth.eu/envoy-internal: allow
        egress.samoth.eu/database: allow
        ingress.samoth.eu/kube-apiserver: allow
        egress.samoth.eu/kube-apiserver: allow
      podAnnotations:
        reloader.stakater.com/auto: "true"
      env:
        - name: AUTHENTIK_POSTGRESQL__DISABLE_SERVER_SIDE_CURSORS
          value: "true"
        - name: AUTHENTIK_POSTGRESQL__SSLMODE
          value: require
        - name: AUTHENTIK_POSTGRESQL__CONN_HEALTH_CHECKS
          value: "true"
    
    authentik:
      error_reporting:
        enabled: false
      disable_update_check: true
      disable_startup_analytics: true
      postgresql:
        host: pooler-transaction-rw.database.svc.cluster.local.
        name: "authentik"
        port: 5432

    server:
      replicas: 2
      pdb: &pdb
        enabled: true
        minAvailable: 1
      podLabels: &podLabels
        ingress.samoth.eu/vmagent: allow
      metrics: &metrics
        enabled: true
        serviceMonitor:
          enabled: true
          scrapeTimeout: 10s
      route:
        main:
          enabled: true
          hostnames:
            - authentik.${SECRET_DOMAIN}
          parentRefs:
            - name: envoy-internal
              namespace: network

    worker:
      replicas: 2
      pdb: *pdb
      podLabels: *podLabels
      metrics: *metrics
      resources:
        limits:
          memory: 1Gi

    prometheus:
      rules:
        enabled: true

    postgresql:
      enabled: false
    redis:
      enabled: false

  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: AUTHENTIK_SECRET_KEY
      targetPath: authentik.secret_key
    - kind: Secret
      name: postgres-user-authentik
      valuesKey: username
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: postgres-user-authentik
      valuesKey: password
      targetPath: authentik.postgresql.password