---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${APP}
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  chartRef:
    kind: OCIRepository
    name: ${APP}
  interval: 1h
  values:
    controllers:
      openssh:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/openssh-server
              tag: 10.2_p1-r0-ls220
            env:
              PUID: 1000
              PGID: 1000
              TZ: Europe/Paris
            envFrom:
              - secretRef:
                  name: ${APP}-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 1m
                memory: 25Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      labels:
        ingress.samoth.eu/lan: allow
        # TODO fix this
        ingress.samoth.eu/kube-apiserver: allow
        egress.samoth.eu: deny
    service:
      app:
        controller: openssh
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "${SECRET_LB3_IPV4}"
          lbipam.cilium.io/sharing-key: "media"
        ports:
          ssh:
            port: 2222
            protocol: TCP
            targetPort: 2222
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      hdd1:
        enabled: true
        type: hostPath
        hostPath: /var/mnt/hdd1
        hostPathType: Directory
        advancedMounts:
          openssh:
            app:
              - path: /var/mnt/hdd1