apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-secret
stringData:
  SERVER_PASSWORD: ENC[AES256_GCM,data:pUpjWnl3Mbe6,iv:m95JH2s8/6lin2WbL7GL8HdEJFcGRrDKM+nTAhjZiIA=,tag:YhEC8GqBw7ZjgzP8xizQ5Q==,type:str] #ENC[AES256_GCM,data:xHZxaq1ywSqglb/NrxPb1ufuTRp4DSkzWg==,iv:dYV63Q9RciFcCcKkDUCq6s2AYWhy7greE9wqxdSYw8Q=,tag:IgvBIrgHNJbSsmxVBcGi+w==,type:comment]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:0M57ae2FWl5F,iv:J2DGvo/6hVkaAeQmMpkEXW7WOB8iPyGW12sS3AgUZ54=,tag:9eZL3C03Pn8wJ3l/c1vSpA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYVRYSm1DeFpjQjRJSXZp
        VGNaMitMeEtPV2gzMHNta1l0RXZGdEVWUGdzCjYwSG44aVR2WlNrZ3JLMExLejVv
        d2MrTExVcGFtRVA0Q1F6OHRZU01yK1kKLS0tIGFuOHZwaDc5NmZYQkU1V3YrNmRp
        OUhRWmJVNHlkL2ZNYVovQ2tQSnhHMzAKEF7l6Hex8TFw1G5dbvWHiK3LI2seGbjA
        QBrox4GDopLqYL/gHUfEiJa3kz+QsRSa2H5dNeYgzRjvSUQ7+f6GeA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-21T10:10:07Z"
  mac: ENC[AES256_GCM,data:wUHLQEDe2c/AOCwkp+ASuiXYzuFqdSG/VCTpzYJcD3lrDWsBn6LCeZ61YEstDCiAIbiuTKfNqdia7HLmKbutU1dlgoyVjIHxO8MOp4vri/XHtfi67DUs5etPtSuciLkls7M8CiIiqAGaHZg7YO0rmCBSlUj+VFu42B3cU7vbrsM=,iv:S5htQPwo3Po3IBZO0Q0CQ9bBmLPha2+Dy6NOGE6nlic=,tag:kKlwhEol//8oh4WdUNCVFQ==,type:str]
  version: 3.13.1
