---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ${APP}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: ${APP}
  ingress:
    # Envoy
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: network
            gateway.networking.k8s.io/gateway-name: envoy-internal
    # Kube api
    - fromEntities:
        - kube-apiserver
    # Database
    - fromEndpoints: &labels
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: database
            cnpg.io/cluster: postgres
            cnpg.io/podRole: pooler
  egress:
    # Envoy
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: network
            gateway.networking.k8s.io/gateway-name: envoy-internal
    # Kube api
    - toEntities:
        - kube-apiserver
    # Database
    - toEndpoints: *labels
      toPorts:
        - ports:
            - port: "5432"
              protocol: "TCP"