---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${APP}
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 3.7.5
  url: oci://ghcr.io/woodpecker-ci/helm/woodpecker
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  chartRef:
    kind: OCIRepository
    name: ${APP}
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              group: apps
              kind: StatefulSet
            patch: |
              - op: add
                path: /spec/template/metadata/labels/ingress.samoth.eu~1envoy-internal
                value: allow
              - op: add
                path: /spec/template/metadata/labels/ingress.samoth.eu~1kube-apiserver
                value: allow
              - op: add
                path: /spec/template/metadata/labels/egress.samoth.eu~1database
                value: allow
              - op: add
                path: /spec/template/metadata/labels/egress.samoth.eu~1envoy-internal
                value: allow
              - op: add
                path: /spec/template/metadata/labels/egress.samoth.eu~1kube-apiserver
                value: allow
  values:
    agent:
      replicaCount: 2
      env:
        WOODPECKER_SERVER: 'woodpecker-server:9000'
        WOODPECKER_BACKEND: kubernetes
        WOODPECKER_BACKEND_K8S_NAMESPACE: dev
        WOODPECKER_BACKEND_K8S_NAMESPACE_PER_ORGANIZATION: false
        # WOODPECKER_BACKEND_K8S_STORAGE_CLASS: ''
        # WOODPECKER_BACKEND_K8S_VOLUME_SIZE: 10G
        # WOODPECKER_BACKEND_K8S_STORAGE_RWX: true
        # WOODPECKER_BACKEND_K8S_POD_LABELS: ''
        # WOODPECKER_BACKEND_K8S_POD_ANNOTATIONS: ''
        WOODPECKER_CONNECT_RETRY_COUNT: '1'
        WOODPECKER_MAX_WORKFLOWS: 10
      securityContext: &sc
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 512Mi
    server:
      statefulSet:
        replicaCount: 2
      env:
        WOODPECKER_ADMIN: 'samoth69'
        WOODPECKER_HOST: https://woodpecker.${SECRET_DOMAIN}
        WOODPECKER_DATABASE_DRIVER: postgres
        WOODPECKER_DATABASE_DATASOURCE:
          valueFrom:
            secretKeyRef:
              name: postgres-user-${APP}
              key: uri
        WOODPECKER_FORGEJO: true
        WOODPECKER_FORGEJO_URL: https://forgejo.${SECRET_DOMAIN}
        WOODPECKER_FORGEJO_CLIENT:
          valueFrom:
            secretKeyRef:
              name: ${APP}-secret
              key: forgejo-client
        WOODPECKER_FORGEJO_SECRET:
          valueFrom:
            secretKeyRef:
              name: ${APP}-secret
              key: forgejo-secret
      persistentVolume:
        enabled: false
      securityContext: *sc
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 512Mi
