apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-secret
stringData:
  forgejo-client: ENC[AES256_GCM,data:d5q8/SfMq5IZLBVtGNQzuZ5ta652fY5neUJrD7/dFiB39oyo,iv:71kDmp/GdqWlLWoSa/S+F1eEbO2Cki6MvXbkswQIzxE=,tag:8HvF1F7ETYLd+AEIh2mYyg==,type:str]
  forgejo-secret: ENC[AES256_GCM,data:/AHi4AmMXN831dpCzE19g1/vWwvNIsJCWM2ZPWmYWsPKw0GHwox/NBwF8MW8YhmOxZyXwVqo7eE=,iv:e5SGNVxxRrosBSh0mRjaKsINxHdvZkgx0rHKnO53zqw=,tag:kixW8QNhl2yzmE8q7rWUlA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERGlRZUNlcWtxVGNVT3dG
        UFNKWTJjcXlMRmNycmM1U1JKbFpWMlJWRlFvCkVvV0ZPWTlSd0FXUTFBcGVDQ1JK
        VWwySlNCYkEvWERZTkRPcjczemowYkkKLS0tIFlPUURobmdGcEhuV2lzdVBYSUVr
        NmVXQnY5Vlg4ak9zb041eWNtaGNIL28KJLwcYRx7Z1SR5zstFgBluoLsn51laMVQ
        Rg7msCdzpA7PUlfIDmFR9wdKUI+/rnEEb4P9vXC6rjf/85+5Jt1A9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-10T15:13:28Z"
  mac: ENC[AES256_GCM,data:dWa+rLaEqlXHY+6A8o+4zoCEsblTeorvUFcGQOfra4yMqhOPdOu1WqWo9KLPbqeyO8BrMXxzVvChH3TphJUPCYi7Jeqiu+YVE7bAaknMSNwgF+EMoRgOsCwKVjT1zdpO9Vtx2Lx/RuqGZvV9SviNuxhFnexV9G49vYI9lb7lVz8=,iv:sucRW4M/JryKvu5rJqzMCrYgglzGvaHc0HTRE2xTa50=,tag:nV53ldm6uuD+DzhBMqTINQ==,type:str]
  version: 3.13.3
