---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app woodpecker
spec:
  components:
    - ../../../../components/app-network-policy
    - ../../../../components/database
  dependsOn:
    - name: postgres-cnpg
      namespace: database
  path: ./clusters/k4/kubernetes/apps/dev/woodpecker/app
  targetNamespace: &namespace dev
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      NAMESPACE: *namespace
  commonMetadata:
    labels:
      ingress.samoth.eu/envoy-internal: allow
      ingress.samoth.eu/kube-apiserver: allow
      egress.samoth.eu/database: allow
      egress.samoth.eu/envoy-internal: allow
      egress.samoth.eu/kube-apiserver: allow