---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: filebrowser
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.6.2
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app filebrowser
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      filebrowser:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          labels:
            ingress.samoth.eu/envoy-internal: allow
          nodeSelector:
            kubernetes.io/hostname: tatsumi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            runAsNonRoot: true
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        
        containers:
          app:
            image:
              repository: filebrowser/filebrowser
              tag: v2.63.2
            env:
              TZ: Europe/Paris
              FB_DATABASE: /config/filebrowser.db
              FB_ROOT: /srv
              FB_LOG: stdout
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    
    service:
      app:
        controller: filebrowser
        ipFamilyPolicy: RequireDualStack
        ports:
          http:
            targetPort: *port
            port: 80
    
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      hdd1:
        enabled: true
        type: hostPath
        hostPath: /var/mnt/hdd1
        hostPathType: Directory
        globalMounts:
          - path: /srv/hdd1
            readOnly: true