---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: daily
spec:
  moverPodLabels:
    egress.samoth.eu/truenas-nfs: allow
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - tatsumi
          weight: 1
  enabled: true
  trigger:
    schedule: 30 3,15 * * *
  moverVolumes:
    - mountPath: repository
      volumeSource:
        nfs:
          path: /mnt/ThePool/Apps/K4-Volsync
          server: ${SECRET_TRUENAS_IP}
  repository:
    repository: volsync-maintenance