---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${APP}
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.0.1
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  chartRef:
    kind: OCIRepository
    name: ${APP}
  interval: 1h
  values:
    controllers:
      app:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/cross-seed/cross-seed
              tag: 6.13.7
            args:
              - daemon
            env:
              TZ: Europe/Paris
              CROSSSEED_PORT: &port 3000
              CROSSSEED_APIKEY:
                secretKeyRef:
                  name: ${APP}-secret
                  key: api-key
              QBITTORRENT_APIKEY:
                secretKeyRef:
                  name: ${APP}-secret
                  key: qui-qbittorrent-key
              PROWLARR__AUTH__APIKEY:
                secretKeyRef:
                  name: prowlarr-secret
                  key: api-key
              SONARR_ANIME__AUTH__APIKEY:
                secretKeyRef:
                  name: sonarr-anime-secret
                  key: api-key
              SECRET_DOMAIN: ${SECRET_DOMAIN}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 200Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: tatsumi
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        ingress.samoth.eu/envoy-internal: allow
        egress.samoth.eu/envoy-internal: allow
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    
    service:
      app:
        ports:
          http:
            port: *port
    
    route:
      app:
        hostnames:
          - "${APP}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      config-file:
        type: configMap
        name: "${APP}-config"
        globalMounts:
          - path: /config/config.js
            subPath: config.js
      hdd1:
        enabled: true
        type: hostPath
        hostPath: /var/mnt/hdd1
        hostPathType: Directory
        advancedMounts:
          app:
            app:
              - path: /var/mnt/hdd1
                readOnly: true
