apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    api-key: ENC[AES256_GCM,data:ylpda5/bZL2GnBQpAezsyY0BTjvJRuYIvXhrtDmAkqjnFwns+MfUGxOUorItcQndwQU=,iv:seTRClqwEOx9nHqFs/ZlE7HwGcPLvUYhnKETLDir9Zg=,tag:XqkFOMZGHi4CPrkz1ypvJQ==,type:str]
    qui-qbittorrent-key: ENC[AES256_GCM,data:seoTyujzTQsruEpZmDUhqbilfYjw/pWXGEHw3RYIvbBDAoHGmgSoioRUG4VCdR/5qCoMh+2rdaMaRlULgTPqfg==,iv:DV+z5vJZtb3WLCNjsPr98SVJ91jIebmOHmc3ZZHV2rM=,tag:uCX2fImtR8APyjdL4KIixQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeWM5M1VBMC9QUkt0cHZu
            K3dKRXQ5TElHbzRudnRsRU9Takx3bnFUNGtRClF1RkhNcVdZaUhJMmR6RDJPN21t
            dUUyc0hBQmdid3ZVZkJGOWhYSXc1bE0KLS0tIEJ6ajJWb29kOW1kSXd6WHVvbmFI
            dW96RWFUVGZzM2pnQ1d2Mmx1MVY5YlUKvF/ha4msksqdcDbc91Y3DLzN44XF3vev
            hBC6pyyTPGDN5SNRwOxQRb4wshd1elBUvppiM4b1qCLWEHBn+334JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T12:56:29Z"
    mac: ENC[AES256_GCM,data:WsTiwjqGB/bx0ggU1rSF0FMzwTPEEuDTTaOMYKHaMMTWdBpzYIHTGqAPU7k6a3QKfe/VISYb7++3OoHlM7fi6yR7eae3bJkZvfVWbTjBb2utRbe5QKvQuhAcw7p/iDRXHxGK5VpwCqzWyKU7N+h0Ylga/p8l2ZBW75/1W/OUp20=,iv:EIg6mfN+IRQA4AQM2MdYe8Fur5gmJQO1drMhzal62Fw=,tag:9flqsKOqCDLO13II0lvU8A==,type:str]
    version: 3.13.1
