apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    api-key: ENC[AES256_GCM,data:ylpda5/bZL2GnBQpAezsyY0BTjvJRuYIvXhrtDmAkqjnFwns+MfUGxOUorItcQndwQU=,iv:seTRClqwEOx9nHqFs/ZlE7HwGcPLvUYhnKETLDir9Zg=,tag:XqkFOMZGHi4CPrkz1ypvJQ==,type:str]
    qui-qbittorrent-proxy-url: ENC[AES256_GCM,data:wfR593oinzg8f5hDq2BE+Vf5nrdhHMSutjKkT6gGzR/V4d4UMrdP6A4CdzN8ZtPHZFC9znoOfYNkNOpn+jpLUW6N8Yqapy7Vw5mt3YsVZsbfSKL44XdqyRfcM09U0hU=,iv:NfROl35jXrdl5eO54HyuSfd9fx4s+oUxfeinox2Keyo=,tag:puatC7PPzEOXNoomxPaMZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeWM5M1VBMC9QUkt0cHZu
            K3dKRXQ5TElHbzRudnRsRU9Takx3bnFUNGtRClF1RkhNcVdZaUhJMmR6RDJPN21t
            dUUyc0hBQmdid3ZVZkJGOWhYSXc1bE0KLS0tIEJ6ajJWb29kOW1kSXd6WHVvbmFI
            dW96RWFUVGZzM2pnQ1d2Mmx1MVY5YlUKvF/ha4msksqdcDbc91Y3DLzN44XF3vev
            hBC6pyyTPGDN5SNRwOxQRb4wshd1elBUvppiM4b1qCLWEHBn+334JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T14:18:01Z"
    mac: ENC[AES256_GCM,data:5eOkxSVhw+xs9JORUvxZhuOhP7Nm0HcqALn9iPTfHa4Z6Vxz9+98JSYrF8+MT1Y80+upQ6p8I/bFa2ZHT829Y9rdb1/an67wUVIbwhOISVaxKbPFjKC37A3fjuTcjttL+9MsZWYecCy2m7xVAiyplN0RsFi4mDpvNulZZJYlG/Q=,iv:vLTeyKyM02c2SWAr1AzKTe/4w9Yp/yUI7rqJAS6igiU=,tag:KYgaQMdow0nvk+O6frkN2g==,type:str]
    version: 3.13.1
