---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/refs/tags/v8.0.0/schemas/config-schema.json
sonarr:
  anime:
    base_url: https://sonarr-anime.${SECRET_DOMAIN}
    api_key: !env_var SONARR_ANIME_API_KEY
    delete_old_custom_formats: true
    quality_definition:
      type: anime

    quality_profiles:
      - trash_id: 4c48f506c1116a3a57ae33f12346bd15  # [French MULTi.VO] HD Bluray + WEB (1080p)
        reset_unmatched_scores:
          enabled: true
      - trash_id: b34c968f58433a38e0e690d42a1dc37e  # [French VOSTFR] HD Bluray + WEB (1080p)
        reset_unmatched_scores:
          enabled: true

    custom_format_groups:
      ################################################################################
      ## These groups are NOT synced by default. Uncomment to enable. Use `select:` to
      ## choose specific CFs within a group.
      ##
      ## To uncomment, remove `# ` (hash + space) so that indentation stays aligned.
      ## Most editors do this automatically with toggle-comment (Ctrl+/).
      ##
      ## https://recyclarr.dev/guide/cf-groups/
      ################################################################################
      add:
        - trash_id: 848fd356c200568fc5a6248150e7e7ea  # [Streaming Services] French
        - trash_id: f4a0410a1df109a66d6e47dcadcce014  # [Optional] Miscellaneous
          select:
        #     - 32b367365729d530ca1c124a0b180c64  # Bad Dual Groups
        #     - ef4963043b0987f8485bc9106f16db38  # DV (Disk)
        #     - 1bd69272e23c5e6c5b1d6c8a36fce95e  # HFR
            - 7ba05c6e0e14e793538174c679126996  # MULTi
        #     - 82d40da2bc6923f41e14394075dd4b03  # No-RlsGroup
        #     - e1a997ddb54e3ecbfe06341ad323c458  # Obfuscated
        #     - 06d66ab109d4d2eddb2794d21526d140  # Retags
        #     - 1b3994c551cbb92a2c781af061f4ab44  # Scene
        #     - 7470a681e6205243983c4410ee4c920f  # VC-1
        #     - 90501962793d580d011511155c97e4e5  # VP9
        #     - cddfb4e32db826151d97352b8e37c648  # x264
            - c9eafd50846d299b862ca9bb6ea91950  # x265
        #     - 041d90b435ebd773271cea047a457a6a  # x266