---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/refs/tags/v8.5.1/schemas/config-schema.json
sonarr:
  anime:
    base_url: https://sonarr-anime.${SECRET_DOMAIN}
    api_key: !env_var SONARR_ANIME_API_KEY
    delete_old_custom_formats: true
    quality_definition:
      type: anime

    quality_profiles:
      - trash_id: &qp1 4c48f506c1116a3a57ae33f12346bd15  # [French MULTi.VO] HD Bluray + WEB (1080p)
        reset_unmatched_scores:
          enabled: true
      - trash_id: &qp2 b34c968f58433a38e0e690d42a1dc37e  # [French VOSTFR] HD Bluray + WEB (1080p)
        reset_unmatched_scores:
          enabled: true

    custom_formats:
      # We do not want x265 to be tanked in formats
      # So we do two things (in order):
      # - disabling x264
      # - setting custom format "x265 (HD)" to 0, effectively disabling it
      # - setting the standard x265 with a score of 100 (this is an arbitrary number) to make sonarr prioritize x265 content over everything else.
      # - setting av1 even higher
      - trash_ids:
          - cddfb4e32db826151d97352b8e37c648 # x264
        assign_scores_to:
          - trash_id: *qp1
            score: -10000
          - trash_id: *qp2
            score: -10000
      - trash_ids:
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - trash_id: *qp1
            score: 0
          - trash_id: *qp2
            score: 0
      - trash_ids:
          - c9eafd50846d299b862ca9bb6ea91950 # x265
        assign_scores_to:
          - trash_id: *qp1
            score: 100
          - trash_id: *qp2
            score: 100
      - trash_ids:
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
        assign_scores_to:
          - trash_id: *qp1
            score: 200
          - trash_id: *qp2
            score: 200
