---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/refs/tags/v8.5.1/schemas/config-schema.json
sonarr:
  anime:
    base_url: https://sonarr-anime.${SECRET_DOMAIN}
    api_key: !env_var SONARR_ANIME_API_KEY
    delete_old_custom_formats: true
    quality_definition:
      type: anime

    quality_profiles:
      - trash_id: 4c48f506c1116a3a57ae33f12346bd15  # [French MULTi.VO] HD Bluray + WEB (1080p)
        reset_unmatched_scores:
          enabled: true
      - trash_id: b34c968f58433a38e0e690d42a1dc37e  # [French VOSTFR] HD Bluray + WEB (1080p)
        reset_unmatched_scores:
          enabled: true

    custom_format_groups:
      add:
        - trash_id: 4c48f506c1116a3a57ae33f12346bd15  # [French MULTi.VO] HD Bluray + WEB (1080p)
          exclude:
            - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
          select:
            - c9eafd50846d299b862ca9bb6ea91950  # x265
        - trash_id: b34c968f58433a38e0e690d42a1dc37e  # [French VOSTFR] HD Bluray + WEB (1080p)
          exclude:
            - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
          select:
            - c9eafd50846d299b862ca9bb6ea91950  # x265