---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${APP}
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.10.9
  url: oci://ghcr.io/home-operations/charts/kopiur
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  chartRef:
    kind: OCIRepository
    name: ${APP}
  interval: 1h
  values:
    replicaCount: 2
    podLabels: &labels
      ingress.samoth.eu/kube-apiserver: allow
      ingress.samoth.eu/vmagent: allow
      egress.samoth.eu/kube-apiserver: allow
    podDisruptionBudget:
      enabled: true
    monitoring:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
      dashboards:
        enabled: true
    resources:
      requests:
        cpu: 5m
        memory: 80Mi
      limits:
        memory: 200Mi
    webhook:
      enabled: true
      replicaCount: 2
      tls:
        mode: cert-manager
      podLabels: *labels
      podDisruptionBudget:
        enabled: true
      resources:
        requests:
          cpu: 5m
          memory: 32Mi
        limits:
          memory: 128Mi
