# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cilium.io/ciliumcidrgroup_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumCIDRGroup
metadata:
  name: group-lan
spec:
  externalCIDRs:
    - ${SECRET_CIDR_LAN_V4}
    - ${SECRET_CIDR_LAN_V6}
    # https://tailscale.com/docs/concepts/tailscale-ip-addresses
    - 100.64.0.0/10
    # https://tailscale.com/docs/concepts/ip-and-dns-addresses#tailscale-ipv6-local-address-prefix
    - fd7a:115c:a1e0:ab12::/64