# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cilium.io/ciliumcidrgroup_v2.json
apiVersion: cilium.io/v2
kind: CiliumCIDRGroup
metadata:
  name: group-lan
spec:
  externalCIDRs:
    - ${SECRET_CIDR_LAN_V4}
    - ${SECRET_CIDR_LAN_V6}