# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: namespace-isolated-network-policy
spec:
  description: "Allow nothing in ingress and allow only dns in egress for the namespace where this object is created"
  endpointSelector:
    matchLabels:
      {}
  ingress:
    - {}
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts: &port
        - ports:
            - port: "53"
              protocol: "ANY"
          rules:
            dns:
              - matchPattern: "*"
    # # TODO figure out why Cilium doesn't always map kube-dns properly
    # - toCIDR:
    #     - fd00:69::a/128
    #     - 10.69.0.10/32
    #   toPorts: *port