# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: node-feature-discovery
spec:
  endpointSelector:
    matchLabels: &labels
      app.kubernetes.io/instance: node-feature-discovery
  ingress:
    - fromEntities:
        - kube-apiserver
    - fromEndpoints:
        - matchLabels: *labels
    # VMAgent
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
            app.kubernetes.io/name: vmagent
            app.kubernetes.io/component: monitoring
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egress:
    - toEntities:
        - kube-apiserver
    - toEndpoints:
      - matchLabels: *labels