---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-gluetun
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  refreshInterval: 168h # 1 week
  target:
    name: qbittorrent-gluetun-secret
    template:
      data:
        apiKey: "{{ .password }}"
        auth.toml: |
          [[roles]]
          name = "gluetun-qb-port-sync"
          routes = [
            "GET /v1/publicip/ip",
            "GET /v1/openvpn/portforwarded"
          ]
          auth = "apikey"
          apikey = "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: generator-qbittorrent-gluetun