---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
configMapGenerator:
  - name: qbittorrent-coredns
    files:
      - ./config/Corefile
configurations:
  - ./config/kustomizeconfig.yaml
generatorOptions:
  disableNameSuffixHash: true