---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./networkpolicy.yaml
  - ./password.yaml
configMapGenerator:
  - name: qbittorrent-coredns
    files:
      - ./config/Corefile
configurations:
  - ./config/kustomizeconfig.yaml
generatorOptions:
  disableNameSuffixHash: true