apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
stringData:
    SERVER_COUNTRIES: ENC[AES256_GCM,data:CR/6WEM9,iv:4pRMK1TClkEZDkYo9hUPe6oSYBHwEukdUxQ1XxZLF84=,tag:GPiWoaqdH9yVtAHvJF3e7g==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:xumQcuLVtbpy,iv:MCbgpA1KTFpWCmVsUQ2BTStvW1FIRfMyMviWLXlZVDE=,tag:P1bX/Xu9XHgmDUaAGCsfJA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:0tghEofGOmfjdaCpVc1HTXlZidkjeHmA/3Q33v2L1cDEZ2LA6961ijrgi64=,iv:sHgbQheDuiuC8RO6i/FArpPveDhQO1HrXRbpQ/QyK8c=,tag:4XV9oBnArNq0oL7nCTvlEw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ZTJmEYH7wMiG7a64edk61xHssaET8JhnlzvfRzD36nkPERLFpNn61USBt1I=,iv:WBXGWrb/UyhNaXqy0zENV5q/3XnRPRMyrsGdUr4k1Z0=,tag:ouL4RNF0XSsRMR8ldE2ftA==,type:str]
sops:
    age:
        - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRTBHY0pZZEU2Y3JKMVpi
            amxrc2l5ejZ4Z2JWZkZwUkdwa0Eyb1FXV3lJCnZuTWFFQ1JNL0lvdnZtdElxWHpV
            U2I1emYxdWNIREpCRzdCZmlCeU9QNkUKLS0tIGFwazJwME51aVlZWUo1OFBNSnMx
            TTRBT20zanhtOEZOa2FKa3k2YlVZQkEKm1ToDFReNmgdeqPMQFiMi+2OGTfrhPo8
            4rlw8Hnza6E4zDSZ1x8CHfOQbXl8BZcta/vssKwv4iGYtiYT//cU+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T14:43:15Z"
    mac: ENC[AES256_GCM,data:7mxzt/JZGlgRaKM75GNA4GTcM8OCC27Zp075wrIiWfWgu/Q8zrvH+a+TSBMy6z9Gx15fru3iRK+Z2fjzq6frIbO4Ps3Vl56YAhUosMXdcRWq9D9ptbGnD7X/fnGS6EJp9L69J+kFxOJfsQnyNXXjR8UHRKeFMaCwb3tsY6oqiZ8=,iv:u2Bu+vbZ+NcQcnUp2Y0d2XipqhQUOU/82myiYNV6dig=,tag:NZ4j2oMDVWlLvAL2VwAX6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
