apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
stringData:
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:qPys+CJbyTJyELGItLXs3ShGCq9UDLs=,iv:3yLs3LjAHGLCPgdn9KYOOjGPMiXb0rM2CKsAWNticpQ=,tag:hnFswoBVNdgFp7hOPtdkKw==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:7+nHC/E=,iv:fx+1cWMGUs3anR/09B76DBgptBVK5RWziWxftV9uS9g=,tag:wSEHpUXcg31UncADgHJLMA==,type:int]
    VPN_PORT_FORWARDING_PROVIDER: ENC[AES256_GCM,data:+R6bUUeMNQdu,iv:kJRdMZss3o/4snTYXYxpoKiaENmHwJ3iUpNQeD6G+Eg=,tag:ebF4W04ViM/vrHviLeg9xQ==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:0tghEofGOmfjdaCpVc1HTXlZidkjeHmA/3Q33v2L1cDEZ2LA6961ijrgi64=,iv:sHgbQheDuiuC8RO6i/FArpPveDhQO1HrXRbpQ/QyK8c=,tag:4XV9oBnArNq0oL7nCTvlEw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ZTJmEYH7wMiG7a64edk61xHssaET8JhnlzvfRzD36nkPERLFpNn61USBt1I=,iv:WBXGWrb/UyhNaXqy0zENV5q/3XnRPRMyrsGdUr4k1Z0=,tag:ouL4RNF0XSsRMR8ldE2ftA==,type:str]
sops:
    age:
        - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRTBHY0pZZEU2Y3JKMVpi
            amxrc2l5ejZ4Z2JWZkZwUkdwa0Eyb1FXV3lJCnZuTWFFQ1JNL0lvdnZtdElxWHpV
            U2I1emYxdWNIREpCRzdCZmlCeU9QNkUKLS0tIGFwazJwME51aVlZWUo1OFBNSnMx
            TTRBT20zanhtOEZOa2FKa3k2YlVZQkEKm1ToDFReNmgdeqPMQFiMi+2OGTfrhPo8
            4rlw8Hnza6E4zDSZ1x8CHfOQbXl8BZcta/vssKwv4iGYtiYT//cU+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T12:32:03Z"
    mac: ENC[AES256_GCM,data:y5VIDeVrjmHLqpjKT2GTVAtV6IENHyCCE3bcRQ2Mw+f1myhyaibs8tRT1Bpm2nha8jty886ir5haNy+iNT042jVrqgzx/9D1vvCdPouSYIF7KvSxPRmnuW/WYkX+6xQVlHDuQEqtPuBw9+myV3Mx057ndYDxJKJJPv0vWg+7x0Y=,iv:WBRuFZ42SWpILmKLWWNThwSOPMogp2KCA333x0KK5cs=,tag:dVUw1FTnrYVtAj/2liSSwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
