apiVersion: v1
kind: Secret
metadata:
    name: samba-secret
stringData:
    samba.yaml: ENC[AES256_GCM,data:x/KbqtvZcNx9NSQp5Xsaz3jA17QAd2h0A9ipat3LFK69Y4YRQm0NMZd4ZqzUvsERbjN4OO5v0DDfAfDIhvy3yBZfc/QNzAAo+kFwxIFSX5QOIcVZoStqJBRt2Mq6qjYfm8zkpyssy2uR17OapYnKGwhqfjrV7pVvcjwzQPW7vF3crqhGnUw8gDyo8onwohbR3ZAtc1WQ2wvdysB+SzF8Fcr/TiwWRsMf4vQUHmS0Bx3bsezf3xtT37RJHPBAEMTS0mOQpn3K8FCFKWOLROfAOi+Md5zZ+XSdN0d7qfEA1OQE6lep5fUg033k11kpcbfF4v4Mf2mSZUc/3RKlU4YK/9zQqUC37xD6MXOq34lc/T5BCoYn639d5BXbHMd3h/mlnr3cpurtKlX/VK8LufdbDTHC6/fFXwjX29fCEIJnpVRYMET1icn9fTPmnvGw98gS0w==,iv:2/9c1XpFZ7mk7EGueAu33EX+jtUAOypsV4SATmr55jQ=,tag:5dHnDoidX6s2hemtNynYgQ==,type:str]
sops:
    age:
        - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeWM5M1VBMC9QUkt0cHZu
            K3dKRXQ5TElHbzRudnRsRU9Takx3bnFUNGtRClF1RkhNcVdZaUhJMmR6RDJPN21t
            dUUyc0hBQmdid3ZVZkJGOWhYSXc1bE0KLS0tIEJ6ajJWb29kOW1kSXd6WHVvbmFI
            dW96RWFUVGZzM2pnQ1d2Mmx1MVY5YlUKvF/ha4msksqdcDbc91Y3DLzN44XF3vev
            hBC6pyyTPGDN5SNRwOxQRb4wshd1elBUvppiM4b1qCLWEHBn+334JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T18:20:43Z"
    mac: ENC[AES256_GCM,data:f1/MTd/Z6QiEAmz074kBYS0iTfm8/BzUTO1I6ldE4zznBfUKnP8u1H0OJlpbgFRy6c6GZeqGVztL/sU/JNE2QQRH0h4sKClA6/cnKcFMarHMrKmUiU0b4s5Z7toAxQmrGUhz+1L3QfuHi5On0wIHFJ2X4zOzailY2wqEJFZuUCs=,iv:oOGBDpbges39iLU32GwMyJrwtFvcqMtFp1uI/ON8yAs=,tag:Cl+KAnBRZlZGmSbD586Oug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
