apiVersion: v1
kind: Secret
metadata:
    name: samba-secret
stringData:
    samba.yaml: ENC[AES256_GCM,data:7/y21znKd5xFpzjuHUll4oxRJCHQuVzz00gtW5pPhXi2n28g4kWSVRDn4lZZ+6Pzv4CU5HpcnExLMTIOergVUdXeLii6hT4/zGSFIMU9+O/du8xoL5umDFoARIQEmELszbvXgonl4/mG93e6m8EUSwmjUBoyKuhA9XOiuImtVaKYWvDGwvRqX18I7MDJWmjr+CZd01ckFsFhrzsW/C7ChaCfHESARSEMXQ0YG/yqbzjzkfwROF1mqMm2URrdVWOwIAqP3wLfD6xch1vz7nSFBvzcGzsRfnsaBc1JU65ydquY2C8FkEMPr61c00LAqZtr/bQXJesFRPqzc+B8IMJeNPuTBOBuGq+FKRSQpUPbBVQeHopJ7zD9lIzT96dNijHzlOAogQSmZyYWJOe2Kp+XVnBGj6Av1lPNZOOOtTP3Lf/LS0pk7svXc9avVfXLDFq8E4hc1PI=,iv:OWJEEGIMnS9luk93HfQ1oUxr9KLChdz4Mjvg/8+/698=,tag:g1ruBpa+awhbttJYb+taCg==,type:str]
sops:
    age:
        - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeWM5M1VBMC9QUkt0cHZu
            K3dKRXQ5TElHbzRudnRsRU9Takx3bnFUNGtRClF1RkhNcVdZaUhJMmR6RDJPN21t
            dUUyc0hBQmdid3ZVZkJGOWhYSXc1bE0KLS0tIEJ6ajJWb29kOW1kSXd6WHVvbmFI
            dW96RWFUVGZzM2pnQ1d2Mmx1MVY5YlUKvF/ha4msksqdcDbc91Y3DLzN44XF3vev
            hBC6pyyTPGDN5SNRwOxQRb4wshd1elBUvppiM4b1qCLWEHBn+334JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T18:11:35Z"
    mac: ENC[AES256_GCM,data:ON1yrv6bwPr0qSeXWylUS9JbH6hyAerN4UWj6erbOMTShQD77FzvZYtdwoE+dlPv7isFpD6zNZm97LOBxe6C2O2RXuMxnM5+M3j4X7zJGU/uErVD6akaqyJNbqS6b7RjLtrSRm1tGWFvc2T5sPk9iF22Qb9+2/KEItGWXfQiGrk=,iv:hrSVSEWrhD8u1dqo6r0+vcy20L8qdnOhu0ikwRWjMaY=,tag:FdwuM+8ILCyqJftVpx+lSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
