apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    LLDAP_LDAP_BASE_DN: ENC[AES256_GCM,data:hiXb5bX6l8GQpSotl/CF,iv:YVKirNwLJebHL7gu0BlSbpT2zE+Pk1KiU1NZBZzMkMI=,tag:HYTXrgJGTUt5zLgwLJQsGw==,type:str]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:GD1iCem1CYohittBBeRdbcrT/kHRw48RUNvjVZ6jjCseyhCuCogQLYB01Ufsvff/k75Nph+IUSFPR0L0pqWvxA==,iv:CiZeArppSvdU0/wm5ihFJszckRsQgOjhZT2DBdGiKV0=,tag:p668of8YXxwWp9AIR4/sBQ==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:sWaTnCr4cwG09iFKS9SplJqM+DrPfIbFgI2QHG0T8NSF8kEdSYdAsthXy0ucmAU1P1CuOVCTXDqFj/j6Hpwc2A==,iv:j5HujcHkN41IXQcEt3/VgSBHZ9usGUjZ3z6VQ5r+vzs=,tag:cYZfgWStJTQAvM2wH2+Bbg==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:2G4dWi7w7XBKDbtefhVMqQJ3GQrJggmEHeOBJ0yVHd8BF3v8Vhash0i5/4wqKeswj/blVbtYnxB/lnW88xTDtQ==,iv:34gFxbUvos850ifaWn9Va10oW5CpiNojXnumNdrK1oc=,tag:64dpBPSYvhXySoYSY07k6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY2ZXdG1LMUlFVUh3cHBS
            UW9wZE5sbldPWDFHZXIxWmtGUXpKRUdmMWhNCnQrOVNCbTI0RVdVajduUXpVdFFo
            d0QwNUZ5SW82MlpEYnlaYStVaWk3dXMKLS0tIG11R3M4REhiSEVlUjJMd0dGSjdI
            WkpBMDM1MklaOEc5S2VvMjI3dm1OcHMKMN9wKmMSNVnCP3ljlRDApQYntF7uY/jD
            DBr/1WpaAeVSxbzq2XbT+4eNsotG7rhFImPcBz23gpQqXF8LtLnysA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T12:05:57Z"
    mac: ENC[AES256_GCM,data:apefeJ75dajwYLI+bPTon7YcLXDzVeakZZcFgGuC753P5RJG5N7kS4zBCphAFcBftWs8z84dfd7iLIMMIBKizNYjNfY0jfoJiyUfScbFfLv3z9tFSetijvf/uWQyRRiZHNqGpfSGpEsmT/G1BZ8mLiIZQcrLjOhoXdVBXEHQQ4Y=,iv:3S7JJBPkxAIn3o5l5+dOBtfD4xe+IpKOX0XXhfKs/Mc=,tag:JuW5AFLgfJxLH5318z4TUg==,type:str]
    version: 3.13.1
