---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/envoyproxy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-internal
spec:
  ipFamily: DualStack
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyPDB:
        minAvailable: 1
      # TODO figure out why envoy try to fetch a access_log schema from googleapis.com...
      envoyDeployment:
        replicas: 2
        container:
          imageRepository: mirror.gcr.io/envoyproxy/envoy
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 1Gi
        pod:
          labels:
            ingress.samoth.eu/lan: allow
      envoyService:
        externalTrafficPolicy: Cluster
  shutdown:
    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Gzip