---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/envoyproxy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-internal
spec:
  ipFamily: DualStack
  logging:
    level:
      default: debug
  provider:
    type: Kubernetes
    kubernetes:
      envoyPDB:
        minAvailable: 1
      # TODO figure out why envoy try to fetch a access_log schema from googleapis.com...
      envoyDeployment:
        replicas: 2
        container:
          image: mirror.gcr.io/envoyproxy/envoy:v1.38.0
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi
        pod:
          labels:
            ingress.samoth.eu/lan: allow
            egress.samoth.eu/envoy-internal: allow
      envoyService:
        annotations:
          lbipam.cilium.io/ips: "${SECRET_LB_IPV4},${SECRET_LB_IPV6}"
          lbipam.cilium.io/sharing-key: "internal-ingress"
        # Must be cluster when L2 Aware LB are enabled
        externalTrafficPolicy: Cluster
  shutdown:
    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Gzip