apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-secret
stringData:
  USER_NAME: ENC[AES256_GCM,data:yh8qEw9m,iv:DzjOrqpkZuQK2XsG6qfgeZXoxsnqG7H+JOX3HXA+3vI=,tag:qiA7uFNfb6RjEGz29ju1DQ==,type:str]
  PASSWORD_ACCESS: ENC[AES256_GCM,data:2fZ9/Q==,iv:oj+HtrR00mNE5SnIVGlnPBtCJulMHnu6IC/xgsAK9NA=,tag:tT2ffCTgK63FzJAmGwf+yw==,type:bool]
  USER_PASSWORD: ENC[AES256_GCM,data:AjcODR0r4g==,iv:JsQwJr6dvZZmDZ5aNMX8E5NIgJKRgegBwAt85vd/keA=,tag:IIwyS9k077cTXU6NlJ/IqQ==,type:str]
sops:
  age:
    - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWVJVQ2Y0d1Y3dHZqQzNr
        RVc1Ny8rTVU1Q1psaSs1YVo0dE5lNEJYY3lvCmg2WFQrRDBpbWZ1MVJqQ0dyT1R3
        VXU2ZDNDbllVUUx3ZjROaGJ0dFV5M0kKLS0tIHBjNHBOSG9DcnlpM1c1WXJLM3hS
        N0dKYUd0MVNXampxNi8vYXNmenJsNzQKgSx4ArqYgokD9ZvjEKzjOXBKtI2tiTRs
        WWoAKieCUfbBFoytZ6Zk1lMIT1vESwjrX+MMNvhk2R+PFjgkDdN9Kg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T16:17:56Z"
  mac: ENC[AES256_GCM,data:vOOxO+xZivPGynYVDykr8v1LEWMujQSPUGEWpNJNwSUCmdKeEitmHL41u7v0oFHIqyEeBZYcx0DnYNdAKgmKV5Ij385PQplxyODtzfaZXQFfjxYW1Ny5PGjoj61HKifI/gHa65JoYBdRj85L38U5Bki/+VCQasRfz4CMdvN3EJ8=,iv:wC4Mm/BoBQg91vGUGJR4HITvSsFP5mEt/rWMZ9dlQbs=,tag:gymnbcWJG9+7Ks8Zb3QYMg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
