apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    USER_NAME: ENC[AES256_GCM,data:yh8qEw9m,iv:DzjOrqpkZuQK2XsG6qfgeZXoxsnqG7H+JOX3HXA+3vI=,tag:qiA7uFNfb6RjEGz29ju1DQ==,type:str]
    PASSWORD_ACCESS: ENC[AES256_GCM,data:Tp0ZGg==,iv:DhlGMYe2yM0hAJj5jOyTXfGrysFxcqthoG18qYc97RU=,tag:ZSPYIud9eYm/7bYqwee9lw==,type:str]
    USER_PASSWORD: ENC[AES256_GCM,data:AjcODR0r4g==,iv:JsQwJr6dvZZmDZ5aNMX8E5NIgJKRgegBwAt85vd/keA=,tag:IIwyS9k077cTXU6NlJ/IqQ==,type:str]
sops:
    age:
        - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWVJVQ2Y0d1Y3dHZqQzNr
            RVc1Ny8rTVU1Q1psaSs1YVo0dE5lNEJYY3lvCmg2WFQrRDBpbWZ1MVJqQ0dyT1R3
            VXU2ZDNDbllVUUx3ZjROaGJ0dFV5M0kKLS0tIHBjNHBOSG9DcnlpM1c1WXJLM3hS
            N0dKYUd0MVNXampxNi8vYXNmenJsNzQKgSx4ArqYgokD9ZvjEKzjOXBKtI2tiTRs
            WWoAKieCUfbBFoytZ6Zk1lMIT1vESwjrX+MMNvhk2R+PFjgkDdN9Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T16:30:28Z"
    mac: ENC[AES256_GCM,data:1/fiofhMVh5ddH0NTAz/lrE/W36VGj2DNmwLVVUnPLJkrpiPR+MF+jdJp0frsM43siJI3LpCzCPS6ecBfWwSkNLJfnf0a/XAsQgzVkeCQXLYv3izslGVVz4cRZhDLKEyDYlD1moh3VJe1o8ujvs1ei+wzGJdpdo2/cFvamacOo8=,iv:N7H+W8ew8q141ziepGsBjeazSK+UwkphG0Z9G8kt5v8=,tag:Cm/Y6kadyi4uHPYEQhyvWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
