all:
  children:
    # distros
    raspbian:
      hosts:
        PiHoleGamma:
          ansible_host: 192.168.0.2
        PiHoleEpsilon:
          ansible_host: 192.168.0.3
    rocky:
      hosts:
        LabDMZ:
          ansible_host: 192.168.0.36
    proxmox:
      hosts:
        Akame:
          ansible_ssh_user: root
          ansible_host: 192.168.0.5
  
    docker:
      hosts:
        PiHoleGamma:
        PiHoleEpsilon:
        LabDMZ:

    dns_server:
      hosts:
        PiHoleGamma:
        PiHoleEpsilon:

    nut:
      hosts:
        Akame:
        PiHoleGamma:

    doco_cd:
      hosts:
        PiHoleGamma:
        PiHoleEpsilon: