---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/prometheusrule_v1.json
# https://github.com/rwlove/home-ops/blob/main/kubernetes/apps/observability/kube-prometheus-stack/app/prometheusrule-cilium-drops.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cilium-policy-drops
spec:
  groups:
    - name: cilium-policy-drops
      rules:
        - alert: CiliumPolicyDropsSustained
          annotations:
            description: >-
              CiliumNetworkPolicy is dropping {{ $value | humanize }} pkt/s (sustained 10m+).
              App {{ $labels.source }} using {{ $labels.protocol }} with destination {{ $labels.destination }}
            summary: Sustained CiliumNetworkPolicy drops into {{ $labels.source }}.
          expr: |
            sum by (source, destination, protocol) (
              rate(hubble_drop_total{reason="POLICY_DENIED"}[5m])
            ) > 0.083
          for: 10m
          labels:
            severity: warning
        - alert: CiliumPolicyDropBurst
          annotations:
            description: >-
              CiliumNetworkPolicy is dropping {{ $value | humanize }} pkt/s (sustained 10m+).
              App {{ $labels.source }} using {{ $labels.protocol }} with destination {{ $labels.destination }}
            summary: CiliumNetworkPolicy drop burst into {{ $labels.source }}.
          expr: |
            sum by (source, destination, protocol) (
              rate(hubble_drop_total{reason="POLICY_DENIED"}[5m])
            ) > 0.083
          for: 2m
          labels:
            severity: warning