---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-operator
spec:
  dependsOn:
    - name: prometheus-operator-crds
  interval: 1h
  path: ./clusters/k4/kubernetes/apps/monitoring/victoria-metrics/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: monitoring
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-logs
spec:
  dependsOn:
    - name: victoria-metrics-operator
  interval: 1h
  path: ./clusters/k4/kubernetes/apps/monitoring/victoria-metrics/logs
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: monitoring
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vmks
spec:
  dependsOn:
    - name: victoria-metrics-operator
  interval: 1h
  path: ./clusters/k4/kubernetes/apps/monitoring/victoria-metrics/metrics
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: monitoring
  wait: false
