---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qbittorrent-openssh-server
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-ceph-cluster
      namespace: storage
  interval: 1h
  path: ./clusters/k4/kubernetes/apps/media/qbittorrent-openssh-server/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: true
  components:
    - ../../../../components/volsync