---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: policy-reporter
spec:
  interval: 1h
  url: https://kyverno.github.io/policy-reporter
  timeout: 3m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
spec:
  interval: 30m
  chart:
    spec:
      chart: policy-reporter
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
  values:
    podLabels:
      ingress.samoth.eu/envoy-internal: allow
    httproute:
      enabled: true
      hostnames:
        - kyverno.${SECRET_DOMAIN}
      parentRefs:
        - name: envoy-internal
          namespace: network
    ui:
      enabled: true
