authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 1m
  ldap:
    implementation: "lldap"
    start_tls: false
    address: "ldap://lldap.security.svc.cluster.local:389"
    base_dn: "DC=samoth,DC=eu"
    user: "UID=authelia,OU=people,DC=samoth,DC=eu"
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_search_mode: filter
    attributes:
      username: uid
      display_name: displayName
      group_name: cn
      mail: mail
      member_of: memberOf

session:
  same_site: lax
  inactivity: 2h
  expiration: 1d
  remember_me: 2M
  cookies:
    - name: samoth_session
      domain: ${SECRET_DOMAIN}
      authelia_url: https://${APP}.${SECRET_DOMAIN}
      default_redirection_url: https://${SECRET_DOMAIN}

notifier:
  disable_startup_check: true
  # TODO find a way to send an email without it being a headache
  filesystem:
    filename: '/tmp/notification.txt'

totp:
  disable: false
  issuer: authelia.com

webauthn:
  disable: true

duo_api:
  disable: true

definitions:
  network:
    internal:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
    trusted:
      - "${SECRET_CIDR_LAN_V4}"
      - "${SECRET_CIDR_LAN_V6}"