authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 1m
  ldap:
    implementation: "lldap"
    address: "ldap://lldap.security.svc.cluster.local:389"
    base_dn: "DC=samoth,DC=eu"
    user: "UID=authelia,OU=people,DC=samoth,DC=eu"

session:
  same_site: lax
  inactivity: 2h
  expiration: 1d
  remember_me: 2M
  cookies:
    - name: samoth_session
      domain: ${SECRET_DOMAIN}
      authelia_url: https://${APP}.${SECRET_DOMAIN}

notifier:
  disable_startup_check: true
  # TODO find a way to send an email without it being a headache
  filesystem:
    filename: '/tmp/notification.txt'

totp:
  disable: false
  issuer: authelia.com

webauthn:
  disable: true

duo_api:
  disable: true

definitions:
  network:
    internal:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
    trusted:
      - "${SECRET_CIDR_LAN_V4}"
      - "${SECRET_CIDR_LAN_V6}"

access_control:
  default_policy: one_factor
  rules:
    - networks:
        - internal
        - trusted
      policy: one_factor
      domain: "*.${SECRET_DOMAIN}"

identity_providers:
  oidc:
    authorization_policies:
      default:
        default_policy: deny
        rules:
          - networks:
              - internal
              - trusted
            policy: one_factor
    jwks:
      - key: {{ secret "/config/secret/JWKS_KEY_SECRET" | mindent 10 "|" | msquote }}
        use: 'sig'
    cors:
      endpoints:
        - "authorization"
        - "token"
        - "revocation"
        - "introspection"
    clients:
      - client_name: qui
        client_id: qui
        client_secret: '{{ env "QUI_OIDC_CLIENT_SECRET" }}'
        public: false
        authorization_policy: default
        require_pkce: false
        redirect_uris:
          - https://qui.${SECRET_DOMAIN}/api/auth/oidc/callback
        scopes:
          - openid
          - profile
          - groups
          - email
        response_types:
          - code
        grant_types:
          - authorization_code
        access_token_signed_response_alg: none
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_basic