apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    api-key: ENC[AES256_GCM,data:DsTqwpgopdaCYRBvDTxL6r2D03FlLHgK5KV13sXAMNzij3TMFlZr9FZFHd7mjS6N,iv:DC6cc+MzKljD/ylUQWaxhl2I5ZUMA6lGL+u7xpCulwg=,tag:pkBLa9tfwxPZDQ/SsCQ0+A==,type:str]
    client-secret: ENC[AES256_GCM,data:PkkCSrQtJjjk1XJe3Y73YJrZSaONUsA5+sa297DTvEqqfeeaEGoRYWYOvRF7ZqNsswPA8vsLEPe7EbwLv4GN1AODD607WDsok7NZJ+do+Te9bgkJi/y5qwj2hagk8vSDvYpXCKie262NYFFcMrT0+DcdBCeWMsmGR2k62/W7sa0=,iv:sERHsMPqes5eU+sItXP6fuvlM3QgyhlG3oB/VkGaF1c=,tag:Fnm97NCAkgtQ2z8tqmKVXw==,type:str]
sops:
    age:
        - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeWM5M1VBMC9QUkt0cHZu
            K3dKRXQ5TElHbzRudnRsRU9Takx3bnFUNGtRClF1RkhNcVdZaUhJMmR6RDJPN21t
            dUUyc0hBQmdid3ZVZkJGOWhYSXc1bE0KLS0tIEJ6ajJWb29kOW1kSXd6WHVvbmFI
            dW96RWFUVGZzM2pnQ1d2Mmx1MVY5YlUKvF/ha4msksqdcDbc91Y3DLzN44XF3vev
            hBC6pyyTPGDN5SNRwOxQRb4wshd1elBUvppiM4b1qCLWEHBn+334JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T12:46:06Z"
    mac: ENC[AES256_GCM,data:DivQDkAfpykkhUAhlEs7hvNtJXox3LU2TqeDHcjRo2k4ujC5S5bKTnPEd3IcVZWF74ioXyAJxNKcdFeXdZElUmjeknQFeaIAEIpLD3/xWI+rOIB+YFt2MEq3zVDzCQiIiD09TuTmmpGliEgrbCrEldwbyLI4vXVblruFnWA9tQY=,iv:6OQbKUFYitgTXxa/dNjNboe5fQT8oGNbqxYMuweBI+Q=,tag:qG1WJWT9v4tg5crK01kvww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
