---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo
spec:
  components:
    - ../../../../components/oauth2
    - ../../../../components/database
    - ../../../../components/valkey
    - ../../../../components/volsync
  dependsOn:
    - name: postgres-cnpg
      namespace: database
    - name: volsync
      namespace: system
  path: ./clusters/k4/kubernetes/apps/dev/forgejo/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
      KANIDM_REDIRECT_PATH: /user/oauth2/kanidm/callback
      KANIDM_SECRET_ROTATION: "false"
  targetNamespace: dev
