# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_EXTERNAL_DOMAIN//./-}"
spec:
  secretName: "${SECRET_EXTERNAL_DOMAIN//./-}-tls"
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod-shortlived
  commonName: "${SECRET_EXTERNAL_DOMAIN}"
  dnsNames:
    - "${SECRET_EXTERNAL_DOMAIN}"
    - "*.${SECRET_EXTERNAL_DOMAIN}"
  duration: 160h
  usages: ["digital signature"]
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
