apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:jtJGBzX+8NzMOPuHZaYPVgfzwOQ6TUm0UoGVH8fwVlsietee6inDLQ==,iv:aOkGHXt5bdbxCDLtxv39zDZ0RIE9W3eGSjUKcnQV5ZE=,tag:RbMryHEd5dt2sow2KDidEw==,type:str]
sops:
  age:
    - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVUxlVkhyVmQ1QWFjS0ha
        NEl2ODV0NzN0WGZPMEdjbkd4bXpOSEw1U21JCjQwN3FTa21ocDg3Sit0Sy9oU3py
        MFQ2UE9sV2dhNjJNSlRLRUIvMCtNemsKLS0tIGl4N214L1RhZm1wQXl0eFVKbEpX
        L3lFUW9JOUtObVY3ZW5YODFQN3lMMlkK69l4KX2bl2hbA59qbfoCdnjfHofB/nd6
        39XynecVfPIELwtNWONryZbkM1ANLrjYtJRZwGFNWHKsFBNMfW+U+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T21:18:52Z"
  mac: ENC[AES256_GCM,data:bXexDa8QQaH83Ua/KiMx7ZfwYv/GNn7OaDa9m9UUx0zq3BYrj0z7sXGLHl7rTIlwjgB3FHlriTZWWyIq3BSxdNDPYTvWJnlZBeTCqjd9f8buICKJ806T5x7ol0fsqGow52s4cSAY9gmnveyy8kR0++wGPuBasGx2N/vl3pgbqJA=,iv:CDvEHBfXHm/6jKM1VXektppnpZhNBoHLhqXxbD9u/s0=,tag:TYh3AGOxqLB2w2TVFlF+BA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
