---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: PiHoleGamma
    group: dns
    url: 192.168.0.2
    interval: 1m
    dns:
      query-name: "${SECRET_GATUS_MONITORING_DOMAIN}"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
  - name: PiHoleDelta
    group: dns
    url: 192.168.0.3
    interval: 1m
    dns:
      query-name: "${SECRET_GATUS_MONITORING_DOMAIN}"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
  
  - name: HomeAssistant
    group: iot
    url: ${SECRET_HOME_ASSISTANT_URL}
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

metrics: true
storage:
  type: postgres
  path: $${POSTGRES_URI}
  caching: true
ui:
  title: Status | Gatus
  header: Status
  link: https://github.com/Samoth69/HomeOps
  buttons:
    - name: Github
      link: https://github.com/Samoth69/HomeOps
web:
  port: $${GATUS_WEB_PORT}