---
alerting:
  discord:
    webhook-url: ${SECRET_GATUS_DISCORD_WEBHOOK}

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: PiHoleGamma
    group: dns
    url: 192.168.0.2
    interval: 1m
    dns:
      query-name: "${SECRET_GATUS_MONITORING_DOMAIN}"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
    alerts:
      - type: discord
        description: "PiHoleGamma is down"
        send-on-resolved: true
  - name: PiHoleDelta
    group: dns
    url: 192.168.0.3
    interval: 1m
    # Nebula-sync window
    maintenance-windows:
      - start: "04:00"
        duration: 10m
        timezone: "Europe/Paris"
        every:
          - Sunday
    dns:
      query-name: "${SECRET_GATUS_MONITORING_DOMAIN}"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
    alerts:
      - type: discord
        description: "PiHoleDelta is down"
        send-on-resolved: true
  
  - name: HomeAssistant
    group: iot
    url: ${SECRET_HOME_ASSISTANT_URL}
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        description: "HomeAssistant is down"
        send-on-resolved: true

  - name: Cloudflare IPv4
    group: connectivity
    url: icmp://1.1.1.1
    interval: 2m
    conditions:
      - "[CONNECTED] == true"
  # - name: Cloudflare IPv6
  #   group: connectivity
  #   url: icmp://[2606:4700:4700::1111]
  #   interval: 2m
  #   client:
  #     network: ip6
  #   conditions:
  #     - "[CONNECTED] == true"
  
  - name: Google IPv4
    group: connectivity
    url: icmp://8.8.8.8
    interval: 2m
    conditions:
      - "[CONNECTED] == true"
  # - name: Google IPv6
  #   group: connectivity
  #   url: icmp://[2001:4860:4860::8888]
  #   interval: 2m
  #   client:
  #     network: ip6
  #   conditions:
  #     - "[CONNECTED] == true"

  - name: Quad9 IPv4
    group: connectivity
    url: icmp://9.9.9.9
    interval: 2m
    conditions:
      - "[CONNECTED] == true"
  # - name: Quad9 IPv6
  #   group: connectivity
  #   url: icmp://[2620:fe::fe]
  #   interval: 2m
  #   client:
  #     network: ip6
  #   conditions:
  #     - "[CONNECTED] == true"

metrics: true
storage:
  type: postgres
  path: $${POSTGRES_URI}
  caching: true
ui:
  title: Status | Gatus
  header: Status
  link: https://github.com/Samoth69/HomeOps
  buttons:
    - name: Github
      link: https://github.com/Samoth69/HomeOps
web:
  port: $${GATUS_WEB_PORT}