apiVersion: v1
kind: Secret
metadata:
  name: kopiur-truenas-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:6gLgnPkDm627csjbgjhmLWnrouufrQHx9fgTxeZ00laLWDTLb5shwp+IGTabkM1z,iv:UO1qnsJm/ISG4tOgYYDInfzAESiS+KI2RnATi9tfj1I=,tag:ue3Hy8/KmfMqdzwFDufQ0Q==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:zUdmRhk2li43OT+KFJ+aAuWqNmhddyyUQXrTkA==,iv:nYGcwe+yy82DnuQd8Xg5SbZtzvfO+yQa7v5OcKda3vk=,tag:U96scPGUvuAODLicXVAFnA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbGJwL2pmTE91MjhRd1Bu
        bWp5T2ZCYm9vUitmZ3dqT2NiOGtGbjhhTmcwCndDeVRhc1dpcEVra0VidnErZ3BF
        bTJ3WVo1eE5jeENPYThCRHYrdlc5dlUKLS0tIEY2bVJwbUNnYUVzUEJjM3dSb28y
        Uys2VVk4KzgzTlRrQ0VkYlVNa0MrcEUKbRYk49NyyBJTScvfsLovCdGVSPygYHS7
        vMk0hpwzyLP713RVZ4K4+b8KunVaMNaoqL8GFM2mm/SEpPMUwZvfGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T13:26:01Z"
  mac: ENC[AES256_GCM,data:dV3C8vlBz13cXVXqcst1jxsaYaHKCESOGOdQco1aQBBA0OL6wtzGOLVqTir6CP/o26ysnxp3sNVDmx9t5o3Kymp+P8qk1kqdtEo59MDWRT9p8JZdJi4FR/6QEn8wousEAvReRsIG/1axoTvE99NfZVkSrmpVcCjjQzFH/tw0IxI=,iv:JflYX29GL23qX/sKuyQZePqkMw/V+3x3Jwfe644Xva4=,tag:KSzV/LdGev9xbZ7l2ZbwXQ==,type:str]
  version: 3.13.3
