apiVersion: v1
kind: Secret
metadata:
    name: kopiur-garage-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:6gLgnPkDm627csjbgjhmLWnrouufrQHx9fgTxeZ00laLWDTLb5shwp+IGTabkM1z,iv:UO1qnsJm/ISG4tOgYYDInfzAESiS+KI2RnATi9tfj1I=,tag:ue3Hy8/KmfMqdzwFDufQ0Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:WQX03l712M/Qpx7QZkC8NuUJMiuIgkQhOdM=,iv:eCqtlRJaBtVuP3S/t/tUHOtD0Em5LL3vr5OyRFVHfQo=,tag:WpJEamJd37RvOFIsNGtBxQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QJ7+ZUAOOgFng/06xu/s+gIt+IcAbJiUW+OO8WSdPjyTWZPx+K19OSpzna+2I5XsU/YlE2mpJob63HOHFZuWag==,iv:jQvytl+hMxGByqtDiyyaS3gkq6sSKfLvsCy8PAhF1To=,tag:RTFMhhrVf2XYr6qS7Mu2Ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbGJwL2pmTE91MjhRd1Bu
            bWp5T2ZCYm9vUitmZ3dqT2NiOGtGbjhhTmcwCndDeVRhc1dpcEVra0VidnErZ3BF
            bTJ3WVo1eE5jeENPYThCRHYrdlc5dlUKLS0tIEY2bVJwbUNnYUVzUEJjM3dSb28y
            Uys2VVk4KzgzTlRrQ0VkYlVNa0MrcEUKbRYk49NyyBJTScvfsLovCdGVSPygYHS7
            vMk0hpwzyLP713RVZ4K4+b8KunVaMNaoqL8GFM2mm/SEpPMUwZvfGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T16:53:34Z"
    mac: ENC[AES256_GCM,data:Y+HQjjQ6xhxlPpWIM7RUIT1PngAq/g7u3wYPSl5BjwlP7XCkJhIWYxVW1kK8W13eeFRgPNfgyzjCu+geZLszZ/Vnl9JkvSaxsFHHQf15WTDrTZ7j3j7vHorJm+CRivEMNRSUNl739EwF/Fb1FTBN8lGbS0zzPIJ3Yk7854sRJdY=,iv:IWn7ftCc2nXvI7+eYGwDjPCVuHrT+Ilehnldu+90+cY=,tag:uWM5l0l9sJPkcNI40oRgig==,type:str]
    version: 3.13.3
