apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    api-key: ENC[AES256_GCM,data:cJryje/B3iVrvGMf1Dz/5LmximzTRajarYEcGzBqnJPibjP7GfM/WRTGg1XCpD3e,iv:A7nqLznlYpNrNLqF/JTXy4S5AmtYy1K+afamvwYHLLU=,tag:RhkK4WFImDB7/wdGshY3mA==,type:str]
sops:
    age:
        - recipient: age1emjn2wlxmsgdeu04uwgvlp4s8a8uwtcyg9g89v550z4zjt7jy3gqu6vw93
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeWM5M1VBMC9QUkt0cHZu
            K3dKRXQ5TElHbzRudnRsRU9Takx3bnFUNGtRClF1RkhNcVdZaUhJMmR6RDJPN21t
            dUUyc0hBQmdid3ZVZkJGOWhYSXc1bE0KLS0tIEJ6ajJWb29kOW1kSXd6WHVvbmFI
            dW96RWFUVGZzM2pnQ1d2Mmx1MVY5YlUKvF/ha4msksqdcDbc91Y3DLzN44XF3vev
            hBC6pyyTPGDN5SNRwOxQRb4wshd1elBUvppiM4b1qCLWEHBn+334JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T16:07:41Z"
    mac: ENC[AES256_GCM,data:Z9r4yCAZ8Lz1p5KaxD5XWK9+DaCSO2ZIY7Jfnsf+dnD2Cn8MtBjVDcXdNDCYF0xHvYi84GcifEKQ9own8UapFkwk4EykEfSZO9RRMCjMQXHRxvRQDfkXwbXmVxyCyNtL24oGB4suDY117dkRkYwuj3mPWIXNjCuBWkbI0WLSROk=,iv:L6J1N6IH8ISmB42q1bGjPjwBfbFLR8+8DtCih2xqWZw=,tag:c0A+tDPRZ2Ortrq6fOSJFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
