# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: namespace-network-policy
spec:
  description: "Allow pod inside this namespace to talk to each others, deny external (outside of namespace) trafic"
  endpointSelector:
    matchLabels:
      {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            {}
  egress:
    - toEndpoints:
        - matchLabels:
            {}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-dns
spec:
  endpointSelector:
    matchLabels:
      {}
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: "ANY"
          rules:
            dns:
              - matchPattern: "*"
    # Mandatory for L7 filtering to work
    - toFQDNs:
        - matchPattern: "*.*.svc.cluster.local."
        - matchPattern: "*.*.*.svc.cluster.local."
        - matchPattern: "*.*.*.*.svc.cluster.local."
        - matchPattern: "*.*.*.*.*.svc.cluster.local."
        - matchPattern: "*.*.*.*.*.*.svc.cluster.local."