---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-${APP}
spec:
  refreshInterval: 168h # 1 week
  target:
    name: postgres-${APP}
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
        pgpass: "pooler-rw.database.svc.cluster.local:5432:${APP}:${APP}:{{ .password }}"
        jdbc-uri: "jdbc:postgresql://pooler-rw.database.svc.cluster.local:5432/${APP}?password={{ .password }}&user=${APP}"
        uri: "postgresql://${APP}:{{ .password }}@pooler-rw.database.svc.cluster.local:5432/${APP}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: generator-postgres-${APP}