---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/fluxcd.controlplane.io/resourceset_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: postgres-cnpg
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  inputStrategy:
    name: Permute
  inputs:
    - role: pooler-rw
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      selector:
        matchLabels:
          postgresql.cnpg.io/role: "true"
  resourcesTemplate: |
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: postgres-cnpg
      namespace: &namespace database
    spec:
      decryption:
        provider: sops
      dependsOn:
        - name: cnpg
        - name: plugin-barman-cloud
      healthChecks:
        - apiVersion: postgresql.cnpg.io/v1
          kind: Cluster
          name: postgres
          namespace: database
      interval: 1h
      path: ./clusters/k4/kubernetes/apps/database/postgres/cnpg
      postBuild:
        substituteFrom:
          - name: cluster-secrets
            kind: Secret
      prune: true
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      targetNamespace: database
      wait: false
      patches:
        - target:
            kind: Cluster
            group: postgresql.cnpg.io
            version: v1
          patch: |-
            apiVersion: postgresql.cnpg.io/v1
            kind: Cluster
            metadata:
              name: not-used
            spec:
              managed:
                roles:
                  <<- $roleNames := list >>
                  <<- range $k, $in := inputs >>
                  <<-   if kindIs "map" $in >>
                  <<-     $r := index $in "role" >>
                  <<-     if $r >>
                  <<-       $roleNames = concat $roleNames (list $r) >>
                  <<-     end >>
                  <<-   end >>
                  <<- end >>
                  <<- $roleNames = $roleNames | compact | uniq | sortAlpha >>

                  <<- $roleObjs := list >>
                  <<- range $r := $roleNames >>
                  <<-   $roleObjs = concat $roleObjs (list (dict
                        "name" $r
                        "ensure" "present"
                        "login" true
                        "superuser" false
                        "passwordSecret" (dict
                          "name" (print "postgres-user-" $r)
                        )
                      )) >>
                  <<- end >>

                  <<- toYaml $roleObjs | nindent 18 >>